// Copyright (c) 2017, 2020 Qualcomm Technologies, Inc.  All Rights Reserved.
// Qualcomm Technologies Proprietary and Confidential.
// This class provides an object for callback testing.
//
#pragma once
// AUTOGENERATED FILE: DO NOT EDIT

#include <stdint.h>
#include "object.h"

#define CTestCBack_UID UINT32_C(0x00FF000E)


