// Copyright (c) 2016, 2020 Qualcomm Technologies, Inc.  All Rights Reserved.
// Qualcomm Technologies Proprietary and Confidential.
// Test interface
#pragma once
// AUTOGENERATED FILE: DO NOT EDIT

#include <stdint.h>
#include "object.h"

#define TestGetSet_OP_get 0
#define TestGetSet_OP_set 1

static inline int32_t
TestGetSet_release(Object self)
{
  return Object_invoke(self, Object_OP_release, 0, 0);
}

static inline int32_t
TestGetSet_retain(Object self)
{
  return Object_invoke(self, Object_OP_retain, 0, 0);
}

static inline int32_t
TestGetSet_get(Object self, uint32_t *vo_ptr, void *bo_ptr, size_t bo_len, size_t *bo_lenout, Object *oo_ptr)
{
  ObjectArg a[3];
  a[0].b = (ObjectBuf) { vo_ptr, sizeof(uint32_t) };
  a[1].b = (ObjectBuf) { bo_ptr, bo_len * 1 };

  int32_t result = Object_invoke(self, TestGetSet_OP_get, a, ObjectCounts_pack(0, 2, 0, 1));

  *bo_lenout = a[1].b.size / 1;
  *oo_ptr = a[2].o;

  return result;
}

static inline int32_t
TestGetSet_set(Object self, uint32_t vi_val, const void *bi_ptr, size_t bi_len, Object oi_val)
{
  ObjectArg a[3];
  a[0].b = (ObjectBuf) { &vi_val, sizeof(uint32_t) };
  a[1].bi = (ObjectBufIn) { bi_ptr, bi_len * 1 };
  a[2].o = oi_val;

  return Object_invoke(self, TestGetSet_OP_set, a, ObjectCounts_pack(2, 0, 1, 0));
}



