#ifndef __I2C_DEFINES_H__
#define __I2C_DEFINES_H__


/*=============================================================================   
    @file  i2c_config.h
    @brief interface to device configuration
   
    Copyright (c) 2021 Qualcomm Technologies, Incorporated.
                        All rights reserved.
    Qualcomm Technologies, Confidential and Proprietary.
===============================================================================*/

/*=============================================================================
                              EDIT HISTORY
 when       who     what, where, why
 --------   ---     -----------------------------------------------------------
 06/10/21   ph      Added new include file.
=============================================================================*/


// NOTE: QUPs are numbered starting from 0 as per the IO sheet
#define ENABLE_QUP_05


// north [se0 - se7] [0:7]
#define QUPV3_0_CORE_BASE_ADDRESS        0x00900000
#define QUPV3_0_CORE_COMMON_BASE_ADDRESS 0x009C0000

// east [se0 - se5] [8:13]
#define QUPV3_1_CORE_BASE_ADDRESS        0x00A00000
#define QUPV3_1_CORE_COMMON_BASE_ADDRESS 0x00AC0000

// south [se0 - se5] [14:19]
#define QUPV3_2_CORE_BASE_ADDRESS        0x00800000
#define QUPV3_2_CORE_COMMON_BASE_ADDRESS 0x008C0000

#define TLMM_GPIO_CFG(gpio, func, dir, pull, drive) \
                          (((gpio) & 0x3FF) << 4  | \
                           ((func) & 0xF  ) << 0  | \
                           ((dir)  & 0x1  ) << 14 | \
                           ((pull) & 0x3  ) << 15 | \
                           ((drive)& 0xF  ) << 17)

#define TLMM_GPIO_INPUT     0x0
#define TLMM_GPIO_PULL_UP   0x3
#define TLMM_GPIO_2MA       0x0

#define QUP_0   0
#define QUP_1   1
#define QUP_2   2

//
// CONFIGURATION START ============================================
//
#define TOP_QUP_00_SDA TLMM_GPIO_CFG(0,  1, TLMM_GPIO_INPUT, TLMM_GPIO_PULL_UP, TLMM_GPIO_2MA)
#define TOP_QUP_00_SCL TLMM_GPIO_CFG(1,  1, TLMM_GPIO_INPUT, TLMM_GPIO_PULL_UP, TLMM_GPIO_2MA)

#define TOP_QUP_01_SDA TLMM_GPIO_CFG(4,  1, TLMM_GPIO_INPUT, TLMM_GPIO_PULL_UP, TLMM_GPIO_2MA)
#define TOP_QUP_01_SCL TLMM_GPIO_CFG(5,  1, TLMM_GPIO_INPUT, TLMM_GPIO_PULL_UP, TLMM_GPIO_2MA)

#define TOP_QUP_02_SDA TLMM_GPIO_CFG(8,  1, TLMM_GPIO_INPUT, TLMM_GPIO_PULL_UP, TLMM_GPIO_2MA)
#define TOP_QUP_02_SCL TLMM_GPIO_CFG(9,  1, TLMM_GPIO_INPUT, TLMM_GPIO_PULL_UP, TLMM_GPIO_2MA)

#define TOP_QUP_03_SDA TLMM_GPIO_CFG(12,  1, TLMM_GPIO_INPUT, TLMM_GPIO_PULL_UP, TLMM_GPIO_2MA)
#define TOP_QUP_03_SCL TLMM_GPIO_CFG(13,  1, TLMM_GPIO_INPUT, TLMM_GPIO_PULL_UP, TLMM_GPIO_2MA)

#define TOP_QUP_04_SDA TLMM_GPIO_CFG(16,  1, TLMM_GPIO_INPUT, TLMM_GPIO_PULL_UP, TLMM_GPIO_2MA)
#define TOP_QUP_04_SCL TLMM_GPIO_CFG(17,  1, TLMM_GPIO_INPUT, TLMM_GPIO_PULL_UP, TLMM_GPIO_2MA)

#define TOP_QUP_05_SDA TLMM_GPIO_CFG(206,  1, TLMM_GPIO_INPUT, TLMM_GPIO_PULL_UP, TLMM_GPIO_2MA)
#define TOP_QUP_05_SCL TLMM_GPIO_CFG(207,  1, TLMM_GPIO_INPUT, TLMM_GPIO_PULL_UP, TLMM_GPIO_2MA)

#define TOP_QUP_06_SDA TLMM_GPIO_CFG(20,  1, TLMM_GPIO_INPUT, TLMM_GPIO_PULL_UP, TLMM_GPIO_2MA)
#define TOP_QUP_06_SCL TLMM_GPIO_CFG(21,  1, TLMM_GPIO_INPUT, TLMM_GPIO_PULL_UP, TLMM_GPIO_2MA)

#define TOP_QUP_07_SDA TLMM_GPIO_CFG(24,  1, TLMM_GPIO_INPUT, TLMM_GPIO_PULL_UP, TLMM_GPIO_2MA)
#define TOP_QUP_07_SCL TLMM_GPIO_CFG(25,  1, TLMM_GPIO_INPUT, TLMM_GPIO_PULL_UP, TLMM_GPIO_2MA)

#define TOP_QUP_08_SDA TLMM_GPIO_CFG(28,  1, TLMM_GPIO_INPUT, TLMM_GPIO_PULL_UP, TLMM_GPIO_2MA)
#define TOP_QUP_08_SCL TLMM_GPIO_CFG(29,  1, TLMM_GPIO_INPUT, TLMM_GPIO_PULL_UP, TLMM_GPIO_2MA)

#define TOP_QUP_09_SDA TLMM_GPIO_CFG(32,  1, TLMM_GPIO_INPUT, TLMM_GPIO_PULL_UP, TLMM_GPIO_2MA)
#define TOP_QUP_09_SCL TLMM_GPIO_CFG(33,  1, TLMM_GPIO_INPUT, TLMM_GPIO_PULL_UP, TLMM_GPIO_2MA)

#define TOP_QUP_10_SDA TLMM_GPIO_CFG(36,  1, TLMM_GPIO_INPUT, TLMM_GPIO_PULL_UP, TLMM_GPIO_2MA)
#define TOP_QUP_10_SCL TLMM_GPIO_CFG(37,  1, TLMM_GPIO_INPUT, TLMM_GPIO_PULL_UP, TLMM_GPIO_2MA)

#define TOP_QUP_11_SDA TLMM_GPIO_CFG(40,  1, TLMM_GPIO_INPUT, TLMM_GPIO_PULL_UP, TLMM_GPIO_2MA)
#define TOP_QUP_11_SCL TLMM_GPIO_CFG(41,  1, TLMM_GPIO_INPUT, TLMM_GPIO_PULL_UP, TLMM_GPIO_2MA)

#define TOP_QUP_12_SDA TLMM_GPIO_CFG(44,  1, TLMM_GPIO_INPUT, TLMM_GPIO_PULL_UP, TLMM_GPIO_2MA)
#define TOP_QUP_12_SCL TLMM_GPIO_CFG(45,  1, TLMM_GPIO_INPUT, TLMM_GPIO_PULL_UP, TLMM_GPIO_2MA)

#define TOP_QUP_13_SDA TLMM_GPIO_CFG(48,  1, TLMM_GPIO_INPUT, TLMM_GPIO_PULL_UP, TLMM_GPIO_2MA)
#define TOP_QUP_13_SCL TLMM_GPIO_CFG(49,  1, TLMM_GPIO_INPUT, TLMM_GPIO_PULL_UP, TLMM_GPIO_2MA) //QUP1 SE5

#define TOP_QUP_14_SDA TLMM_GPIO_CFG(52,  1, TLMM_GPIO_INPUT, TLMM_GPIO_PULL_UP, TLMM_GPIO_2MA) //QUP2 SE0
#define TOP_QUP_14_SCL TLMM_GPIO_CFG(53,  1, TLMM_GPIO_INPUT, TLMM_GPIO_PULL_UP, TLMM_GPIO_2MA)

#define TOP_QUP_15_SDA TLMM_GPIO_CFG(56,  1, TLMM_GPIO_INPUT, TLMM_GPIO_PULL_UP, TLMM_GPIO_2MA)
#define TOP_QUP_15_SCL TLMM_GPIO_CFG(57,  1, TLMM_GPIO_INPUT, TLMM_GPIO_PULL_UP, TLMM_GPIO_2MA)

#define TOP_QUP_16_SDA TLMM_GPIO_CFG(60,  1, TLMM_GPIO_INPUT, TLMM_GPIO_PULL_UP, TLMM_GPIO_2MA)
#define TOP_QUP_16_SCL TLMM_GPIO_CFG(61,  1, TLMM_GPIO_INPUT, TLMM_GPIO_PULL_UP, TLMM_GPIO_2MA)

#define TOP_QUP_17_SDA TLMM_GPIO_CFG(64,  1, TLMM_GPIO_INPUT, TLMM_GPIO_PULL_UP, TLMM_GPIO_2MA)
#define TOP_QUP_17_SCL TLMM_GPIO_CFG(65,  1, TLMM_GPIO_INPUT, TLMM_GPIO_PULL_UP, TLMM_GPIO_2MA)

#define TOP_QUP_18_SDA TLMM_GPIO_CFG(68,  1, TLMM_GPIO_INPUT, TLMM_GPIO_PULL_UP, TLMM_GPIO_2MA)
#define TOP_QUP_18_SCL TLMM_GPIO_CFG(69,  1, TLMM_GPIO_INPUT, TLMM_GPIO_PULL_UP, TLMM_GPIO_2MA)

#define TOP_QUP_19_SDA TLMM_GPIO_CFG(72,  1, TLMM_GPIO_INPUT, TLMM_GPIO_PULL_UP, TLMM_GPIO_2MA)
#define TOP_QUP_19_SCL TLMM_GPIO_CFG(73,  1, TLMM_GPIO_INPUT, TLMM_GPIO_PULL_UP, TLMM_GPIO_2MA) //QUP2 SE5

#define TOP_QUP_20_SDA TLMM_GPIO_CFG(76, 1, TLMM_GPIO_INPUT, TLMM_GPIO_PULL_UP, TLMM_GPIO_2MA)
#define TOP_QUP_20_SCL TLMM_GPIO_CFG(77, 1, TLMM_GPIO_INPUT, TLMM_GPIO_PULL_UP, TLMM_GPIO_2MA)

#define TOP_QUP_21_SDA TLMM_GPIO_CFG(80, 1, TLMM_GPIO_INPUT, TLMM_GPIO_PULL_UP, TLMM_GPIO_2MA)
#define TOP_QUP_21_SCL TLMM_GPIO_CFG(81, 1, TLMM_GPIO_INPUT, TLMM_GPIO_PULL_UP, TLMM_GPIO_2MA)



#endif
