// Copyright (c) 2021, Qualcomm Technologies Inc. All rights reserved.

#define IORT_WORLD_ID_NON_SECURE 0x0
#define IORT_WORLD_ID_SECURE     0x1
#define IORT_WORLD_ID_SHIFT      31

#define IORT_DYNAMIC_MAPPING_NO          0x0
#define IORT_DYNAMIC_MAPPING_YES_DEFAULT 0x0
#define IORT_DYNAMIC_MAPPING_YES         0x1
#define IORT_DYNAMIC_MAPPING_SHIFT       30

#define IORT_TRANSLATION_TYPE_S2_ONLY      0x0
#define IORT_TRANSLATION_TYPE_S2CR_BYPASS  0x1
#define IORT_TRANSLATION_TYPE_SINGLE_STAGE 0x1
#define IORT_TRANSLATION_TYPE_NESTED       0x3
#define IORT_TRANSLATION_TYPE_SHIFT        24

#define IORT_VMID_SHIFT 16

#define ACPI_OEM_ID "QCOM"
#define ACPI_OEM_TABLE_ID 0x51434F4D 0x45444B32
#define ACPI_OEM_REVISION 0x00008998
#define ACPI_CREATOR_ID 0x51434F4D
#define ACPI_CREATOR_REVISION 0x00000001
