#ifndef __SPI_DEFINES_H__
#define __SPI_DEFINES_H__


/*=============================================================================   
    @file  spi_config.h
    @brief interface to device configuration
   
    Copyright (c) 2022 Qualcomm Technologies, Incorporated.
                        All rights reserved.
    Qualcomm Technologies, Confidential and Proprietary.
===============================================================================*/

/*=============================================================================
                              EDIT HISTORY
 when       who     what, where, why
 --------   ---     -----------------------------------------------------------
 01/20/22   BN      Added file for Kailua
 
=============================================================================*/


#define SSC_USE_SPI_01

#define TLMM_GPIO_CFG(gpio, func, dir, pull, drive) \
                          (((gpio) & 0x3FF) << 4  | \
                           ((func) & 0xF  ) << 0  | \
                           ((dir)  & 0x1  ) << 14 | \
                           ((pull) & 0x3  ) << 15 | \
                           ((drive)& 0xF  ) << 17)

#define TLMM_GPIO_INPUT      0x0
#define TLMM_GPIO_OUTPUT     0x1
#define TLMM_GPIO_NO_PULL    0x0
#define TLMM_GPIO_PULL_DOWN  0x1
#define TLMM_GPIO_PULL_UP    0x3
#define TLMM_GPIO_6MA        0x2


#define QUPV3_2_CORE_BASE_ADDRESS        0x00800000
#define QUPV3_2_CORE_COMMON_BASE_ADDRESS 0x008C0000

#define QUPV3_1_CORE_BASE_ADDRESS        0x00A00000
#define QUPV3_1_CORE_COMMON_BASE_ADDRESS 0x00AC0000

// set GPIOs for the defined cores
// TLMM_GPIO_CFG(gpio, func, dir, pull, drive)
#define SPI_01_MISO TLMM_GPIO_CFG(28,  1, TLMM_GPIO_INPUT,  TLMM_GPIO_PULL_DOWN, TLMM_GPIO_6MA)
#define SPI_01_MOSI TLMM_GPIO_CFG(29,  1, TLMM_GPIO_OUTPUT, TLMM_GPIO_PULL_DOWN, TLMM_GPIO_6MA)
#define SPI_01_CLK  TLMM_GPIO_CFG(30,  1, TLMM_GPIO_OUTPUT, TLMM_GPIO_NO_PULL,   TLMM_GPIO_6MA)
#define SPI_01_CS_0 TLMM_GPIO_CFG(31,  1, TLMM_GPIO_OUTPUT, TLMM_GPIO_PULL_DOWN, TLMM_GPIO_6MA)

#define SPI_02_MISO TLMM_GPIO_CFG(32,  1, TLMM_GPIO_INPUT,  TLMM_GPIO_PULL_DOWN, TLMM_GPIO_6MA)
#define SPI_02_MOSI TLMM_GPIO_CFG(33,  1, TLMM_GPIO_OUTPUT, TLMM_GPIO_PULL_DOWN, TLMM_GPIO_6MA)
#define SPI_02_CLK  TLMM_GPIO_CFG(34,  1, TLMM_GPIO_OUTPUT, TLMM_GPIO_NO_PULL,   TLMM_GPIO_6MA)
#define SPI_02_CS_0 TLMM_GPIO_CFG(35,  1, TLMM_GPIO_OUTPUT, TLMM_GPIO_PULL_DOWN, TLMM_GPIO_6MA)

#define SPI_03_MISO TLMM_GPIO_CFG(36,  1, TLMM_GPIO_INPUT,  TLMM_GPIO_PULL_DOWN, TLMM_GPIO_6MA)
#define SPI_03_MOSI TLMM_GPIO_CFG(37,  1, TLMM_GPIO_OUTPUT, TLMM_GPIO_PULL_DOWN, TLMM_GPIO_6MA)
#define SPI_03_CLK  TLMM_GPIO_CFG(38,  1, TLMM_GPIO_OUTPUT, TLMM_GPIO_NO_PULL,   TLMM_GPIO_6MA)
#define SPI_03_CS_0 TLMM_GPIO_CFG(39,  1, TLMM_GPIO_OUTPUT, TLMM_GPIO_PULL_DOWN, TLMM_GPIO_6MA)

#define SPI_04_MISO TLMM_GPIO_CFG(40,  1, TLMM_GPIO_INPUT,  TLMM_GPIO_PULL_DOWN, TLMM_GPIO_6MA)
#define SPI_04_MOSI TLMM_GPIO_CFG(41,  1, TLMM_GPIO_OUTPUT, TLMM_GPIO_PULL_DOWN, TLMM_GPIO_6MA)
#define SPI_04_CLK  TLMM_GPIO_CFG(42,  1, TLMM_GPIO_OUTPUT, TLMM_GPIO_NO_PULL,   TLMM_GPIO_6MA)
#define SPI_04_CS_0 TLMM_GPIO_CFG(43,  1, TLMM_GPIO_OUTPUT, TLMM_GPIO_PULL_DOWN, TLMM_GPIO_6MA)

#define SPI_05_MISO TLMM_GPIO_CFG(44,  1, TLMM_GPIO_INPUT,  TLMM_GPIO_PULL_DOWN, TLMM_GPIO_6MA)
#define SPI_05_MOSI TLMM_GPIO_CFG(45,  1, TLMM_GPIO_OUTPUT, TLMM_GPIO_PULL_DOWN, TLMM_GPIO_6MA)
#define SPI_05_CLK  TLMM_GPIO_CFG(46,  1, TLMM_GPIO_OUTPUT, TLMM_GPIO_NO_PULL,   TLMM_GPIO_6MA)
#define SPI_05_CS_0 TLMM_GPIO_CFG(47,  1, TLMM_GPIO_OUTPUT, TLMM_GPIO_PULL_DOWN, TLMM_GPIO_6MA)

#define SPI_06_MISO TLMM_GPIO_CFG(52,  2, TLMM_GPIO_INPUT,  TLMM_GPIO_PULL_DOWN, TLMM_GPIO_6MA)
#define SPI_06_MOSI TLMM_GPIO_CFG(53,  2, TLMM_GPIO_OUTPUT, TLMM_GPIO_PULL_DOWN, TLMM_GPIO_6MA)
#define SPI_06_CLK  TLMM_GPIO_CFG(54,  2, TLMM_GPIO_OUTPUT, TLMM_GPIO_NO_PULL,   TLMM_GPIO_6MA)
#define SPI_06_CS_0 TLMM_GPIO_CFG(55,  1, TLMM_GPIO_OUTPUT, TLMM_GPIO_PULL_DOWN, TLMM_GPIO_6MA)

#define SPI_07_MISO TLMM_GPIO_CFG(48,  2, TLMM_GPIO_INPUT,  TLMM_GPIO_PULL_DOWN, TLMM_GPIO_6MA)
#define SPI_07_MOSI TLMM_GPIO_CFG(49,  1, TLMM_GPIO_OUTPUT, TLMM_GPIO_PULL_DOWN, TLMM_GPIO_6MA)
#define SPI_07_CLK  TLMM_GPIO_CFG(50,  1, TLMM_GPIO_OUTPUT, TLMM_GPIO_NO_PULL,   TLMM_GPIO_6MA)
#define SPI_07_CS_0 TLMM_GPIO_CFG(51,  1, TLMM_GPIO_OUTPUT, TLMM_GPIO_PULL_DOWN, TLMM_GPIO_6MA)

#define SPI_08_MISO TLMM_GPIO_CFG(24,  1, TLMM_GPIO_INPUT,  TLMM_GPIO_PULL_DOWN, TLMM_GPIO_6MA)
#define SPI_08_MOSI TLMM_GPIO_CFG(25,  1, TLMM_GPIO_OUTPUT, TLMM_GPIO_PULL_DOWN, TLMM_GPIO_6MA)
#define SPI_08_CLK  TLMM_GPIO_CFG(26,  1, TLMM_GPIO_OUTPUT, TLMM_GPIO_NO_PULL,   TLMM_GPIO_6MA)
#define SPI_08_CS_0 TLMM_GPIO_CFG(27,  1, TLMM_GPIO_OUTPUT, TLMM_GPIO_PULL_DOWN, TLMM_GPIO_6MA)

#define SPI_09_MISO TLMM_GPIO_CFG(56,  1, TLMM_GPIO_INPUT,  TLMM_GPIO_PULL_DOWN, TLMM_GPIO_6MA)
#define SPI_09_MOSI TLMM_GPIO_CFG(57,  1, TLMM_GPIO_OUTPUT, TLMM_GPIO_PULL_DOWN, TLMM_GPIO_6MA)
#define SPI_09_CLK  TLMM_GPIO_CFG(58,  1, TLMM_GPIO_OUTPUT, TLMM_GPIO_NO_PULL,   TLMM_GPIO_6MA)
#define SPI_09_CS_0 TLMM_GPIO_CFG(59,  1, TLMM_GPIO_OUTPUT, TLMM_GPIO_PULL_DOWN, TLMM_GPIO_6MA)

#define SPI_10_MISO TLMM_GPIO_CFG(60,  1, TLMM_GPIO_INPUT,  TLMM_GPIO_PULL_DOWN, TLMM_GPIO_6MA)
#define SPI_10_MOSI TLMM_GPIO_CFG(61,  1, TLMM_GPIO_OUTPUT, TLMM_GPIO_PULL_DOWN, TLMM_GPIO_6MA)
#define SPI_10_CLK  TLMM_GPIO_CFG(62,  1, TLMM_GPIO_OUTPUT, TLMM_GPIO_NO_PULL,   TLMM_GPIO_6MA)
#define SPI_10_CS_0 TLMM_GPIO_CFG(63,  1, TLMM_GPIO_OUTPUT, TLMM_GPIO_PULL_DOWN, TLMM_GPIO_6MA)

#define SPI_11_MISO TLMM_GPIO_CFG(64,  1, TLMM_GPIO_INPUT,  TLMM_GPIO_PULL_DOWN, TLMM_GPIO_6MA)
#define SPI_11_MOSI TLMM_GPIO_CFG(65,  1, TLMM_GPIO_OUTPUT, TLMM_GPIO_PULL_DOWN, TLMM_GPIO_6MA)
#define SPI_11_CLK  TLMM_GPIO_CFG(66,  1, TLMM_GPIO_OUTPUT, TLMM_GPIO_NO_PULL,   TLMM_GPIO_6MA)
#define SPI_11_CS_0 TLMM_GPIO_CFG(67,  1, TLMM_GPIO_OUTPUT, TLMM_GPIO_PULL_DOWN, TLMM_GPIO_6MA)

#define SPI_12_MISO TLMM_GPIO_CFG(68,  1, TLMM_GPIO_INPUT,  TLMM_GPIO_PULL_DOWN, TLMM_GPIO_6MA)
#define SPI_12_MOSI TLMM_GPIO_CFG(69,  1, TLMM_GPIO_OUTPUT, TLMM_GPIO_PULL_DOWN, TLMM_GPIO_6MA)
#define SPI_12_CLK  TLMM_GPIO_CFG(70,  1, TLMM_GPIO_OUTPUT, TLMM_GPIO_NO_PULL,   TLMM_GPIO_6MA)
#define SPI_12_CS_0 TLMM_GPIO_CFG(71,  2, TLMM_GPIO_OUTPUT, TLMM_GPIO_PULL_DOWN, TLMM_GPIO_6MA)

#define SPI_13_MISO TLMM_GPIO_CFG(2,   1, TLMM_GPIO_INPUT,  TLMM_GPIO_PULL_DOWN, TLMM_GPIO_6MA)
#define SPI_13_MOSI TLMM_GPIO_CFG(3,   1, TLMM_GPIO_OUTPUT, TLMM_GPIO_PULL_DOWN, TLMM_GPIO_6MA)
#define SPI_13_CLK  TLMM_GPIO_CFG(118, 1, TLMM_GPIO_OUTPUT, TLMM_GPIO_NO_PULL,   TLMM_GPIO_6MA)
#define SPI_13_CS_0 TLMM_GPIO_CFG(119, 1, TLMM_GPIO_OUTPUT, TLMM_GPIO_PULL_DOWN, TLMM_GPIO_6MA)

#define SPI_14_MISO TLMM_GPIO_CFG(80,  1, TLMM_GPIO_INPUT,  TLMM_GPIO_PULL_DOWN, TLMM_GPIO_6MA)
#define SPI_14_MOSI TLMM_GPIO_CFG(81,  1, TLMM_GPIO_OUTPUT, TLMM_GPIO_PULL_DOWN, TLMM_GPIO_6MA)
#define SPI_14_CLK  TLMM_GPIO_CFG(82,  1, TLMM_GPIO_OUTPUT, TLMM_GPIO_NO_PULL,   TLMM_GPIO_6MA)
#define SPI_14_CS_0 TLMM_GPIO_CFG(83,  1, TLMM_GPIO_OUTPUT, TLMM_GPIO_PULL_DOWN, TLMM_GPIO_6MA)

#define SPI_15_MISO TLMM_GPIO_CFG(76,  1, TLMM_GPIO_INPUT,  TLMM_GPIO_PULL_DOWN, TLMM_GPIO_6MA)
#define SPI_15_MOSI TLMM_GPIO_CFG(77,  1, TLMM_GPIO_OUTPUT, TLMM_GPIO_PULL_DOWN, TLMM_GPIO_6MA)
#define SPI_15_CLK  TLMM_GPIO_CFG(78,  1, TLMM_GPIO_OUTPUT, TLMM_GPIO_NO_PULL,   TLMM_GPIO_6MA)
#define SPI_15_CS_0 TLMM_GPIO_CFG(79,  1, TLMM_GPIO_OUTPUT, TLMM_GPIO_PULL_DOWN, TLMM_GPIO_6MA)

#define SPI_16_MISO TLMM_GPIO_CFG(72,  2, TLMM_GPIO_INPUT,  TLMM_GPIO_PULL_DOWN, TLMM_GPIO_6MA)
#define SPI_16_MOSI TLMM_GPIO_CFG(74,  2, TLMM_GPIO_OUTPUT, TLMM_GPIO_PULL_DOWN, TLMM_GPIO_6MA)
#define SPI_16_CLK  TLMM_GPIO_CFG(75,  2, TLMM_GPIO_OUTPUT, TLMM_GPIO_NO_PULL,   TLMM_GPIO_6MA)
#define SPI_16_CS_0 TLMM_GPIO_CFG(106, 2, TLMM_GPIO_OUTPUT, TLMM_GPIO_PULL_DOWN, TLMM_GPIO_6MA)

#endif
