// Copyright (c) 2022 Qualcomm Technologies, Inc.
// All Rights Reserved.
// Confidential and Proprietary - Qualcomm Technologies, Inc.
/**
 * @addtogroup CPeripheralRetainState
 * @{
  Class CPeripheralRetainState implements \link IPeripheralRetainState \endlink interface.
  This class provides interface to notify TZ about RPMB listener ready.
 */
#pragma once
// AUTOGENERATED FILE: DO NOT EDIT

#include <stdint.h>
#include "object.h"

#define CPeripheralRetainState_UID UINT32_C(0x10D)


