#
/*! \file pm_config_target.c
 *
 *  \brief This file contains customizable target specific driver settings & PMIC registers.
 *         This file info is taken from Target Component Resource Specific Settings from PDM
 *         that is maintained for each of the targets separately.
 *
 *  &copy; Copyright 2013 - 2022 QUALCOMM Technologies Incorporated, All Rights Reserved
 */

/* =======================================================================
                             Edit History
  This section contains comments describing changes made to this file.
  Notice that changes are listed in reverse chronological order.

$Header: $
 Version : 1.0
when        who         what, where, why
--------    ---         ---------------------------------------------------
07/09/22    arua      Initial AOP Config
11/10/22    arua      LPI_CX,LPI_MX Max Voltage & Sleep Settings Update
15/10/22    arua      S1F GPIO Control
06/12/22    arua      Dynamic Modem Buck
19/12/22    arua      S9B Max Voltage Update
09/01/23    arua      L11B Driver Owner Mask Update
13/03/23    arua      FR84771 MultiCard Tray
===========================================================================*/

/*===========================================================================

                     INCLUDE FILES

===========================================================================*/

#include "pm_config_interface.h"
#include "pm_config_target.h"

/*
PMIC  Name        SID
A     Tokei       0
B     Bompoka     1
C     Nebula      2 & 3
E     Leica2      4
      SMB1355     I2C
K     Leica2      I2C
L     Leica2      I2C
*/

/*[AccessAllowed, RsrcCategory, AlwaysOn, MinMode, SafetyHR, MinVoltage, MaxVoltage, EnableFixedTime, EnableStepperWarmUpTime, VoltFixedUpTime, VoltFixedDownTime, VoltStepperExtraUpTime, VoltStepperExtraDownTime, VoltDischargeTime, ModeFixedTime , VregReadyEn, VregReadyErrEn, VregWdogTimer]*/
/*[VoltSeqType, EnableSeqType, ModeSeqType, DrvOwnMask, Reserved]*/
__attribute__((section("pm_ddr_reclaim_pool")))
pm_vrm_vreg_rail_info_type ldo_rail_b[] =
{
    {.AccessAllowed = PM_ACCESS_ALLOWED,    .RsrcCategory = VRM_RSRC_REGULATOR,  .AlwaysOn = PM_OFF,  .MinMode = PM_LPM_MODE_VAL,  .SafetyHR = 88,  .MinVoltage = 300,   .MaxVoltage = 650,   .EnableFixedTime = 300, .EnableStepperWarmUpTime = 0, .VoltFixedUpTime = 0, .VoltFixedDownTime = 0, .VoltStepperExtraUpTime = 0,  .VoltStepperExtraDownTime = 0,  .VoltDischargeTime = 0, .ModeFixedTime = 20,  .VregReadyEn = PM_SETTLING_EN, .VregReadyErrEn = PM_SETTLING_ERR_EN,  .VregWdogTimer = VRM_8X_SETTLING_TIMER, .AopHandling = 0, .VoltSeqType = VRM_GENERIC_SEQ, .EnableSeqType = VRM_GENERIC_SEQ, .ModeSeqType = VRM_GENERIC_SEQ, .DrvOwnMask = PM_DRV_DDR, .Reserved = 0}, // L1B VDDIO_EBI, LP4x_LP5_VDDQ
    {.AccessAllowed = PM_ACCESS_ALLOWED,    .RsrcCategory = VRM_RSRC_REGULATOR,  .AlwaysOn = PM_ON,   .MinMode = PM_LPM_MODE_VAL,  .SafetyHR = 72,  .MinVoltage = 312,   .MaxVoltage = 888,   .EnableFixedTime = 300, .EnableStepperWarmUpTime = 0, .VoltFixedUpTime = 0, .VoltFixedDownTime = 0, .VoltStepperExtraUpTime = 20, .VoltStepperExtraDownTime = 20, .VoltDischargeTime = 0, .ModeFixedTime = 20,  .VregReadyEn = PM_SETTLING_EN, .VregReadyErrEn = PM_SETTLING_ERR_EN,  .VregWdogTimer = VRM_8X_SETTLING_TIMER, .AopHandling = 0, .VoltSeqType = VRM_GENERIC_SEQ, .EnableSeqType = VRM_GENERIC_SEQ, .ModeSeqType = VRM_GENERIC_SEQ, .DrvOwnMask = PM_DRV_ARC, .Reserved = 0}, // L2B LPI_CX
    {.AccessAllowed = PM_ACCESS_ALLOWED,    .RsrcCategory = VRM_RSRC_REGULATOR,  .AlwaysOn = PM_OFF,  .MinMode = PM_RET_MODE_VAL,  .SafetyHR = 64,  .MinVoltage = 870,   .MaxVoltage = 970,   .EnableFixedTime = 300, .EnableStepperWarmUpTime = 0, .VoltFixedUpTime = 0, .VoltFixedDownTime = 0, .VoltStepperExtraUpTime = 0,  .VoltStepperExtraDownTime = 0,  .VoltDischargeTime = 0, .ModeFixedTime = 20,  .VregReadyEn = PM_SETTLING_EN, .VregReadyErrEn = PM_SETTLING_ERR_EN,  .VregWdogTimer = VRM_8X_SETTLING_TIMER, .AopHandling = 0, .VoltSeqType = VRM_GENERIC_SEQ, .EnableSeqType = VRM_GENERIC_SEQ, .ModeSeqType = VRM_GENERIC_SEQ, .DrvOwnMask = PM_DRV_DDR, .Reserved = 0}, // L3B VDD2L
    {.AccessAllowed = PM_ACCESS_DISALLOWED, .RsrcCategory = VRM_RSRC_REGULATOR,  .AlwaysOn = PM_OFF,  .MinMode = PM_LPM_MODE_VAL,  .SafetyHR = 0,   .MinVoltage = 530,   .MaxVoltage = 860,   .EnableFixedTime = 300, .EnableStepperWarmUpTime = 0, .VoltFixedUpTime = 0, .VoltFixedDownTime = 0, .VoltStepperExtraUpTime = 0,  .VoltStepperExtraDownTime = 0,  .VoltDischargeTime = 0, .ModeFixedTime = 20,  .VregReadyEn = PM_SETTLING_EN, .VregReadyErrEn = PM_SETTLING_ERR_EN,  .VregWdogTimer = VRM_8X_SETTLING_TIMER, .AopHandling = 0, .VoltSeqType = VRM_GENERIC_SEQ, .EnableSeqType = VRM_GENERIC_SEQ, .ModeSeqType = VRM_GENERIC_SEQ, .DrvOwnMask = PM_DRV_ARC, .Reserved = 0}, // L4B UNUSED
    {.AccessAllowed = PM_ACCESS_ALLOWED,    .RsrcCategory = VRM_RSRC_REGULATOR,  .AlwaysOn = PM_OFF,  .MinMode = PM_LPM_MODE_VAL,  .SafetyHR = 56,  .MinVoltage = 312,   .MaxVoltage = 1052,  .EnableFixedTime = 300, .EnableStepperWarmUpTime = 0, .VoltFixedUpTime = 0, .VoltFixedDownTime = 0, .VoltStepperExtraUpTime = 0,  .VoltStepperExtraDownTime = 0,  .VoltDischargeTime = 0, .ModeFixedTime = 20,  .VregReadyEn = PM_SETTLING_EN, .VregReadyErrEn = PM_SETTLING_ERR_EN,  .VregWdogTimer = VRM_8X_SETTLING_TIMER, .AopHandling = 0, .VoltSeqType = VRM_GENERIC_SEQ, .EnableSeqType = VRM_GENERIC_SEQ, .ModeSeqType = VRM_GENERIC_SEQ, .DrvOwnMask = PM_DRV_ARC|PM_DRV_HLOS, .Reserved = 0}, // L5B MSIP_0P9
    {.AccessAllowed = PM_ACCESS_ALLOWED,    .RsrcCategory = VRM_RSRC_REGULATOR,  .AlwaysOn = PM_OFF,  .MinMode = PM_LPM_MODE_VAL,  .SafetyHR = 64,  .MinVoltage = 751,   .MaxVoltage = 824,   .EnableFixedTime = 300, .EnableStepperWarmUpTime = 0, .VoltFixedUpTime = 0, .VoltFixedDownTime = 0, .VoltStepperExtraUpTime = 0,  .VoltStepperExtraDownTime = 0,  .VoltDischargeTime = 0, .ModeFixedTime = 20,  .VregReadyEn = PM_SETTLING_EN, .VregReadyErrEn = PM_SETTLING_ERR_EN,  .VregWdogTimer = VRM_8X_SETTLING_TIMER, .AopHandling = 0, .VoltSeqType = VRM_GENERIC_SEQ, .EnableSeqType = VRM_GENERIC_SEQ, .ModeSeqType = VRM_GENERIC_SEQ, .DrvOwnMask = PM_DRV_MDMS, .Reserved = 0}, // L6B SDR VDDAL
    {.AccessAllowed = PM_ACCESS_ALLOWED,    .RsrcCategory = VRM_RSRC_REGULATOR,  .AlwaysOn = PM_OFF,  .MinMode = PM_LPM_MODE_VAL,  .SafetyHR = 56,  .MinVoltage = 830,   .MaxVoltage = 920,   .EnableFixedTime = 300, .EnableStepperWarmUpTime = 0, .VoltFixedUpTime = 0, .VoltFixedDownTime = 0, .VoltStepperExtraUpTime = 0,  .VoltStepperExtraDownTime = 0,  .VoltDischargeTime = 0, .ModeFixedTime = 20,  .VregReadyEn = PM_SETTLING_EN, .VregReadyErrEn = PM_SETTLING_ERR_EN,  .VregWdogTimer = VRM_8X_SETTLING_TIMER, .AopHandling = 0, .VoltSeqType = VRM_GENERIC_SEQ, .EnableSeqType = VRM_GENERIC_SEQ, .ModeSeqType = VRM_GENERIC_SEQ, .DrvOwnMask = PM_DRV_HLOS, .Reserved = 0}, // L7B USBSS0P9
    {.AccessAllowed = PM_ACCESS_ALLOWED,    .RsrcCategory = VRM_RSRC_REGULATOR,  .AlwaysOn = PM_ON,   .MinMode = PM_RET_MODE_VAL,  .SafetyHR = 72,  .MinVoltage = 504,   .MaxVoltage = 888,   .EnableFixedTime = 300, .EnableStepperWarmUpTime = 0, .VoltFixedUpTime = 0, .VoltFixedDownTime = 0, .VoltStepperExtraUpTime = 20, .VoltStepperExtraDownTime = 20, .VoltDischargeTime = 0, .ModeFixedTime = 20,  .VregReadyEn = PM_SETTLING_EN, .VregReadyErrEn = PM_SETTLING_ERR_EN,  .VregWdogTimer = VRM_8X_SETTLING_TIMER, .AopHandling = 0, .VoltSeqType = VRM_GENERIC_SEQ, .EnableSeqType = VRM_GENERIC_SEQ, .ModeSeqType = VRM_GENERIC_SEQ, .DrvOwnMask = PM_DRV_ARC, .Reserved = 0}, // L8B LPI_MX
    {.AccessAllowed = PM_ACCESS_DISALLOWED, .RsrcCategory = VRM_RSRC_REGULATOR,  .AlwaysOn = PM_OFF,  .MinMode = PM_LPM_MODE_VAL,  .SafetyHR = 0,   .MinVoltage = 504,   .MaxVoltage = 824,   .EnableFixedTime = 300, .EnableStepperWarmUpTime = 0, .VoltFixedUpTime = 0, .VoltFixedDownTime = 0, .VoltStepperExtraUpTime = 20, .VoltStepperExtraDownTime = 20, .VoltDischargeTime = 0, .ModeFixedTime = 20,  .VregReadyEn = PM_SETTLING_EN, .VregReadyErrEn = PM_SETTLING_ERR_EN,  .VregWdogTimer = VRM_8X_SETTLING_TIMER, .AopHandling = 0, .VoltSeqType = VRM_GENERIC_SEQ, .EnableSeqType = VRM_GENERIC_SEQ, .ModeSeqType = VRM_GENERIC_SEQ, .DrvOwnMask = PM_DRV_ARC, .Reserved = 0}, // L9B UNUSED
    {.AccessAllowed = PM_ACCESS_ALLOWED,    .RsrcCategory = VRM_RSRC_REGULATOR,  .AlwaysOn = PM_OFF,  .MinMode = PM_LPM_MODE_VAL,  .SafetyHR = 56,  .MinVoltage = 824,   .MaxVoltage = 901,   .EnableFixedTime = 300, .EnableStepperWarmUpTime = 0, .VoltFixedUpTime = 0, .VoltFixedDownTime = 0, .VoltStepperExtraUpTime = 0,  .VoltStepperExtraDownTime = 0,  .VoltDischargeTime = 0, .ModeFixedTime = 20,  .VregReadyEn = PM_SETTLING_EN, .VregReadyErrEn = PM_SETTLING_ERR_EN,  .VregWdogTimer = VRM_8X_SETTLING_TIMER, .AopHandling = 0, .VoltSeqType = VRM_GENERIC_SEQ, .EnableSeqType = VRM_GENERIC_SEQ, .ModeSeqType = VRM_GENERIC_SEQ, .DrvOwnMask = PM_DRV_MDMS, .Reserved = 0}, // L10B SDR_MX_PHY_TXDAC_Sub6
    {.AccessAllowed = PM_ACCESS_ALLOWED,    .RsrcCategory = VRM_RSRC_REGULATOR,  .AlwaysOn = PM_OFF,  .MinMode = PM_LPM_MODE_VAL,  .SafetyHR = 48,  .MinVoltage = 312,   .MaxVoltage = 752,   .EnableFixedTime = 300, .EnableStepperWarmUpTime = 0, .VoltFixedUpTime = 0, .VoltFixedDownTime = 0, .VoltStepperExtraUpTime = 0,  .VoltStepperExtraDownTime = 0,  .VoltDischargeTime = 0, .ModeFixedTime = 20,  .VregReadyEn = PM_SETTLING_EN, .VregReadyErrEn = PM_SETTLING_ERR_EN,  .VregWdogTimer = VRM_8X_SETTLING_TIMER, .AopHandling = 0, .VoltSeqType = VRM_GENERIC_SEQ, .EnableSeqType = VRM_GENERIC_SEQ, .ModeSeqType = VRM_GENERIC_SEQ, .DrvOwnMask = PM_DRV_WPSS, .Reserved = 0}, // L11B WCSS_CX
    {.AccessAllowed = PM_ACCESS_ALLOWED,    .RsrcCategory = VRM_RSRC_REGULATOR,  .AlwaysOn = PM_OFF,  .MinMode = PM_LPM_MODE_VAL,  .SafetyHR = 88,  .MinVoltage = 1080,  .MaxVoltage = 1304,  .EnableFixedTime = 300, .EnableStepperWarmUpTime = 0, .VoltFixedUpTime = 0, .VoltFixedDownTime = 0, .VoltStepperExtraUpTime = 0,  .VoltStepperExtraDownTime = 0,  .VoltDischargeTime = 0, .ModeFixedTime = 20,  .VregReadyEn = PM_SETTLING_EN, .VregReadyErrEn = PM_SETTLING_ERR_EN,  .VregWdogTimer = VRM_8X_SETTLING_TIMER, .AopHandling = 0, .VoltSeqType = VRM_GENERIC_SEQ, .EnableSeqType = VRM_GENERIC_SEQ, .ModeSeqType = VRM_GENERIC_SEQ, .DrvOwnMask = PM_DRV_MDMS, .Reserved = 0}, // L12B SDR_VDDAM_Sub6
    {.AccessAllowed = PM_ACCESS_ALLOWED,    .RsrcCategory = VRM_RSRC_REGULATOR,  .AlwaysOn = PM_OFF,  .MinMode = PM_LPM_MODE_VAL,  .SafetyHR = 56,  .MinVoltage = 1080,  .MaxVoltage = 1304,  .EnableFixedTime = 300, .EnableStepperWarmUpTime = 0, .VoltFixedUpTime = 0, .VoltFixedDownTime = 0, .VoltStepperExtraUpTime = 0,  .VoltStepperExtraDownTime = 0,  .VoltDischargeTime = 0, .ModeFixedTime = 20,  .VregReadyEn = PM_SETTLING_EN, .VregReadyErrEn = PM_SETTLING_ERR_EN,  .VregWdogTimer = VRM_8X_SETTLING_TIMER, .AopHandling = 0, .VoltSeqType = VRM_GENERIC_SEQ, .EnableSeqType = VRM_GENERIC_SEQ, .ModeSeqType = VRM_GENERIC_SEQ, .DrvOwnMask = PM_DRV_HLOS, .Reserved = 0}, // L13B UFS VCCQ
    {.AccessAllowed = PM_ACCESS_ALLOWED,    .RsrcCategory = VRM_RSRC_REGULATOR,  .AlwaysOn = PM_OFF,  .MinMode = PM_LPM_MODE_VAL,  .SafetyHR = 48,  .MinVoltage = 1245,  .MaxVoltage = 1304,  .EnableFixedTime = 300, .EnableStepperWarmUpTime = 0, .VoltFixedUpTime = 0, .VoltFixedDownTime = 0, .VoltStepperExtraUpTime = 0,  .VoltStepperExtraDownTime = 0,  .VoltDischargeTime = 0, .ModeFixedTime = 20,  .VregReadyEn = PM_SETTLING_EN, .VregReadyErrEn = PM_SETTLING_ERR_EN,  .VregWdogTimer = VRM_8X_SETTLING_TIMER, .AopHandling = 0, .VoltSeqType = VRM_GENERIC_SEQ, .EnableSeqType = VRM_GENERIC_SEQ, .ModeSeqType = VRM_GENERIC_SEQ, .DrvOwnMask = PM_DRV_WLANRF, .Reserved = 0}, // L14B WCN 1P3
    {.AccessAllowed = PM_ACCESS_DISALLOWED, .RsrcCategory = VRM_RSRC_REGULATOR,  .AlwaysOn = PM_OFF,  .MinMode = PM_LPM_MODE_VAL,  .SafetyHR = 0,   .MinVoltage = 312,   .MaxVoltage = 1304,  .EnableFixedTime = 300, .EnableStepperWarmUpTime = 0, .VoltFixedUpTime = 0, .VoltFixedDownTime = 0, .VoltStepperExtraUpTime = 0,  .VoltStepperExtraDownTime = 0,  .VoltDischargeTime = 0, .ModeFixedTime = 20,  .VregReadyEn = PM_SETTLING_EN, .VregReadyErrEn = PM_SETTLING_ERR_EN,  .VregWdogTimer = VRM_8X_SETTLING_TIMER, .AopHandling = 0, .VoltSeqType = VRM_GENERIC_SEQ, .EnableSeqType = VRM_GENERIC_SEQ, .ModeSeqType = VRM_GENERIC_SEQ, .DrvOwnMask = PM_DRV_ARC, .Reserved = 0}, // L15B UNUSED
    {.AccessAllowed = PM_ACCESS_ALLOWED,    .RsrcCategory = VRM_RSRC_REGULATOR,  .AlwaysOn = PM_OFF,  .MinMode = PM_LPM_MODE_VAL,  .SafetyHR = 56,  .MinVoltage = 312,   .MaxVoltage = 1260,  .EnableFixedTime = 300, .EnableStepperWarmUpTime = 0, .VoltFixedUpTime = 0, .VoltFixedDownTime = 0, .VoltStepperExtraUpTime = 0,  .VoltStepperExtraDownTime = 0,  .VoltDischargeTime = 0, .ModeFixedTime = 20,  .VregReadyEn = PM_SETTLING_EN, .VregReadyErrEn = PM_SETTLING_ERR_EN,  .VregWdogTimer = VRM_8X_SETTLING_TIMER, .AopHandling = 0, .VoltSeqType = VRM_GENERIC_SEQ, .EnableSeqType = VRM_GENERIC_SEQ, .ModeSeqType = VRM_GENERIC_SEQ, .DrvOwnMask = PM_DRV_ARC|PM_DRV_HLOS, .Reserved = 0}, // L16B MSIP_1P2
    {.AccessAllowed = PM_ACCESS_DISALLOWED, .RsrcCategory = VRM_RSRC_REGULATOR,  .AlwaysOn = PM_ON,   .MinMode = PM_LPM_MODE_VAL,  .SafetyHR = 16,  .MinVoltage = 1200,  .MaxVoltage = 1200,  .EnableFixedTime = 300, .EnableStepperWarmUpTime = 0, .VoltFixedUpTime = 0, .VoltFixedDownTime = 0, .VoltStepperExtraUpTime = 0,  .VoltStepperExtraDownTime = 0,  .VoltDischargeTime = 0, .ModeFixedTime = 20,  .VregReadyEn = PM_SETTLING_EN, .VregReadyErrEn = PM_SETTLING_ERR_EN,  .VregWdogTimer = VRM_8X_SETTLING_TIMER, .AopHandling = 0, .VoltSeqType = VRM_GENERIC_SEQ, .EnableSeqType = VRM_GENERIC_SEQ, .ModeSeqType = VRM_GENERIC_SEQ, .DrvOwnMask = PM_DRV_HLOS, .Reserved = 0}, // L17B PMK_VDD_ACT
    {.AccessAllowed = PM_ACCESS_ALLOWED,    .RsrcCategory = VRM_RSRC_REGULATOR,  .AlwaysOn = PM_OFF,  .MinMode = PM_LPM_MODE_VAL,  .SafetyHR = 64,  .MinVoltage = 1504,  .MaxVoltage = 2000,  .EnableFixedTime = 300, .EnableStepperWarmUpTime = 0, .VoltFixedUpTime = 0, .VoltFixedDownTime = 0, .VoltStepperExtraUpTime = 0,  .VoltStepperExtraDownTime = 0,  .VoltDischargeTime = 0, .ModeFixedTime = 20,  .VregReadyEn = PM_SETTLING_EN, .VregReadyErrEn = PM_SETTLING_ERR_EN,  .VregWdogTimer = VRM_8X_SETTLING_TIMER, .AopHandling = 0, .VoltSeqType = VRM_GENERIC_SEQ, .EnableSeqType = VRM_GENERIC_SEQ, .ModeSeqType = VRM_GENERIC_SEQ, .DrvOwnMask = PM_DRV_MDMS, .Reserved = 0}, // L18B SDR VDDAH
    {.AccessAllowed = PM_ACCESS_ALLOWED,    .RsrcCategory = VRM_RSRC_REGULATOR,  .AlwaysOn = PM_OFF,  .MinMode = PM_LPM_MODE_VAL,  .SafetyHR = 80,  .MinVoltage = 1800,  .MaxVoltage = 1950,  .EnableFixedTime = 300, .EnableStepperWarmUpTime = 0, .VoltFixedUpTime = 0, .VoltFixedDownTime = 0, .VoltStepperExtraUpTime = 0,  .VoltStepperExtraDownTime = 0,  .VoltDischargeTime = 0, .ModeFixedTime = 20,  .VregReadyEn = PM_SETTLING_EN, .VregReadyErrEn = PM_SETTLING_ERR_EN,  .VregWdogTimer = VRM_8X_SETTLING_TIMER, .AopHandling = 0, .VoltSeqType = VRM_GENERIC_SEQ, .EnableSeqType = VRM_GENERIC_SEQ, .ModeSeqType = VRM_GENERIC_SEQ, .DrvOwnMask = PM_DRV_HLOS, .Reserved = 0}, // L19B UFS VCCQ2 / eMMC VCCQ
    {.AccessAllowed = PM_ACCESS_ALLOWED,    .RsrcCategory = VRM_RSRC_REGULATOR,  .AlwaysOn = PM_OFF,  .MinMode = PM_LPM_MODE_VAL,  .SafetyHR = 56,  .MinVoltage = 1800,  .MaxVoltage = 1900,  .EnableFixedTime = 300, .EnableStepperWarmUpTime = 0, .VoltFixedUpTime = 0, .VoltFixedDownTime = 0, .VoltStepperExtraUpTime = 0,  .VoltStepperExtraDownTime = 0,  .VoltDischargeTime = 0, .ModeFixedTime = 20,  .VregReadyEn = PM_SETTLING_EN, .VregReadyErrEn = PM_SETTLING_ERR_EN,  .VregWdogTimer = VRM_8X_SETTLING_TIMER, .AopHandling = 0, .VoltSeqType = VRM_GENERIC_SEQ, .EnableSeqType = VRM_GENERIC_SEQ, .ModeSeqType = VRM_GENERIC_SEQ, .DrvOwnMask = PM_DRV_HLOS, .Reserved = 0}, // L20B VDD_BUCK
    {.AccessAllowed = PM_ACCESS_ALLOWED,    .RsrcCategory = VRM_RSRC_REGULATOR,  .AlwaysOn = PM_ON,   .MinMode = PM_NPM_MODE_VAL,  .SafetyHR = 80,  .MinVoltage = 1800,  .MaxVoltage = 2000,  .EnableFixedTime = 300, .EnableStepperWarmUpTime = 0, .VoltFixedUpTime = 0, .VoltFixedDownTime = 0, .VoltStepperExtraUpTime = 0,  .VoltStepperExtraDownTime = 0,  .VoltDischargeTime = 0, .ModeFixedTime = 20,  .VregReadyEn = PM_SETTLING_EN, .VregReadyErrEn = PM_SETTLING_ERR_EN,  .VregWdogTimer = VRM_8X_SETTLING_TIMER, .AopHandling = 0, .VoltSeqType = VRM_GENERIC_SEQ, .EnableSeqType = VRM_GENERIC_SEQ, .ModeSeqType = VRM_GENERIC_SEQ, .DrvOwnMask = PM_DRV_HLOS, .Reserved = 0}, // L21B PX3, PX7, PX2_Alt, IO,QFPROM
    {.AccessAllowed = PM_ACCESS_ALLOWED,    .RsrcCategory = VRM_RSRC_REGULATOR,  .AlwaysOn = PM_OFF,  .MinMode = PM_LPM_MODE_VAL,  .SafetyHR = 80,  .MinVoltage = 1800,  .MaxVoltage = 2000,  .EnableFixedTime = 300, .EnableStepperWarmUpTime = 0, .VoltFixedUpTime = 0, .VoltFixedDownTime = 0, .VoltStepperExtraUpTime = 0,  .VoltStepperExtraDownTime = 0,  .VoltDischargeTime = 0, .ModeFixedTime = 20,  .VregReadyEn = PM_SETTLING_EN, .VregReadyErrEn = PM_SETTLING_ERR_EN,  .VregWdogTimer = VRM_8X_SETTLING_TIMER, .AopHandling = 0, .VoltSeqType = VRM_GENERIC_SEQ, .EnableSeqType = VRM_GENERIC_SEQ, .ModeSeqType = VRM_GENERIC_SEQ, .DrvOwnMask = PM_DRV_MDMS, .Reserved = 0}, // L22B RFFE VDD, VDDIO, EEPROM_VCC
    {.AccessAllowed = PM_ACCESS_ALLOWED,    .RsrcCategory = VRM_RSRC_REGULATOR,  .AlwaysOn = PM_OFF,  .MinMode = PM_LPM_MODE_VAL,  .SafetyHR = 56,  .MinVoltage = 1800,  .MaxVoltage = 1980,  .EnableFixedTime = 300, .EnableStepperWarmUpTime = 0, .VoltFixedUpTime = 0, .VoltFixedDownTime = 0, .VoltStepperExtraUpTime = 0,  .VoltStepperExtraDownTime = 0,  .VoltDischargeTime = 0, .ModeFixedTime = 20,  .VregReadyEn = PM_SETTLING_EN, .VregReadyErrEn = PM_SETTLING_ERR_EN,  .VregWdogTimer = VRM_8X_SETTLING_TIMER, .AopHandling = 0, .VoltSeqType = VRM_GENERIC_SEQ, .EnableSeqType = VRM_GENERIC_SEQ, .ModeSeqType = VRM_GENERIC_SEQ, .DrvOwnMask = PM_DRV_HLOS, .Reserved = 0}, // L23B USBHS1P8, 
    {.AccessAllowed = PM_ACCESS_ALLOWED,    .RsrcCategory = VRM_RSRC_REGULATOR,  .AlwaysOn = PM_OFF,  .MinMode = PM_LPM_MODE_VAL,  .SafetyHR = 448, .MinVoltage = 2700,  .MaxVoltage = 3544,  .EnableFixedTime = 300, .EnableStepperWarmUpTime = 0, .VoltFixedUpTime = 0, .VoltFixedDownTime = 0, .VoltStepperExtraUpTime = 0,  .VoltStepperExtraDownTime = 0,  .VoltDischargeTime = 0, .ModeFixedTime = 20,  .VregReadyEn = PM_SETTLING_EN, .VregReadyErrEn = PM_SETTLING_ERR_DIS, .VregWdogTimer = VRM_8X_SETTLING_TIMER, .AopHandling = 0, .VoltSeqType = VRM_GENERIC_SEQ, .EnableSeqType = VRM_NO_PMIC_SEQ, .ModeSeqType = VRM_GENERIC_SEQ, .DrvOwnMask = PM_DRV_HLOS, .Reserved = 0}, // L24B SD VDD
    {.AccessAllowed = PM_ACCESS_ALLOWED,    .RsrcCategory = VRM_RSRC_REGULATOR,  .AlwaysOn = PM_OFF,  .MinMode = PM_LPM_MODE_VAL,  .SafetyHR = 112, .MinVoltage = 2700,  .MaxVoltage = 3544,  .EnableFixedTime = 300, .EnableStepperWarmUpTime = 0, .VoltFixedUpTime = 0, .VoltFixedDownTime = 0, .VoltStepperExtraUpTime = 0,  .VoltStepperExtraDownTime = 0,  .VoltDischargeTime = 0, .ModeFixedTime = 20,  .VregReadyEn = PM_SETTLING_EN, .VregReadyErrEn = PM_SETTLING_ERR_EN,  .VregWdogTimer = VRM_8X_SETTLING_TIMER, .AopHandling = 0, .VoltSeqType = VRM_GENERIC_SEQ, .EnableSeqType = VRM_GENERIC_SEQ, .ModeSeqType = VRM_GENERIC_SEQ, .DrvOwnMask = PM_DRV_HLOS, .Reserved = 0}, // L25B USBHS_3P1
    {.AccessAllowed = PM_ACCESS_ALLOWED,    .RsrcCategory = VRM_RSRC_REGULATOR,  .AlwaysOn = PM_OFF,  .MinMode = PM_LPM_MODE_VAL,  .SafetyHR = 224, .MinVoltage = 1620,  .MaxVoltage = 3300,  .EnableFixedTime = 300, .EnableStepperWarmUpTime = 0, .VoltFixedUpTime = 0, .VoltFixedDownTime = 0, .VoltStepperExtraUpTime = 0,  .VoltStepperExtraDownTime = 0,  .VoltDischargeTime = 0, .ModeFixedTime = 20,  .VregReadyEn = PM_SETTLING_EN, .VregReadyErrEn = PM_SETTLING_ERR_DIS, .VregWdogTimer = VRM_8X_SETTLING_TIMER, .AopHandling = 0, .VoltSeqType = VRM_GENERIC_SEQ, .EnableSeqType = VRM_GENERIC_SEQ, .ModeSeqType = VRM_GENERIC_SEQ, .DrvOwnMask = PM_DRV_MDMS, .Reserved = 0}, // L26B UIM1
    {.AccessAllowed = PM_ACCESS_ALLOWED,    .RsrcCategory = VRM_RSRC_REGULATOR,  .AlwaysOn = PM_OFF,  .MinMode = PM_LPM_MODE_VAL,  .SafetyHR = 224, .MinVoltage = 1620,  .MaxVoltage = 3300,  .EnableFixedTime = 300, .EnableStepperWarmUpTime = 0, .VoltFixedUpTime = 0, .VoltFixedDownTime = 0, .VoltStepperExtraUpTime = 0,  .VoltStepperExtraDownTime = 0,  .VoltDischargeTime = 0, .ModeFixedTime = 20,  .VregReadyEn = PM_SETTLING_EN, .VregReadyErrEn = PM_SETTLING_ERR_DIS, .VregWdogTimer = VRM_8X_SETTLING_TIMER, .AopHandling = 0, .VoltSeqType = VRM_GENERIC_SEQ, .EnableSeqType = VRM_GENERIC_SEQ, .ModeSeqType = VRM_GENERIC_SEQ, .DrvOwnMask = PM_DRV_MDMS, .Reserved = 0}, // L27B UIM2
    {.AccessAllowed = PM_ACCESS_ALLOWED,    .RsrcCategory = VRM_RSRC_REGULATOR,  .AlwaysOn = PM_OFF,  .MinMode = PM_LPM_MODE_VAL,  .SafetyHR = 8,   .MinVoltage = 1650,  .MaxVoltage = 3300,  .EnableFixedTime = 300, .EnableStepperWarmUpTime = 0, .VoltFixedUpTime = 0, .VoltFixedDownTime = 0, .VoltStepperExtraUpTime = 0,  .VoltStepperExtraDownTime = 0,  .VoltDischargeTime = 0, .ModeFixedTime = 20,  .VregReadyEn = PM_SETTLING_EN, .VregReadyErrEn = PM_SETTLING_ERR_DIS, .VregWdogTimer = VRM_8X_SETTLING_TIMER, .AopHandling = 0, .VoltSeqType = VRM_GENERIC_SEQ, .EnableSeqType = VRM_NO_PMIC_SEQ, .ModeSeqType = VRM_GENERIC_SEQ, .DrvOwnMask = PM_DRV_HLOS, .Reserved = 0}, // L28B PX2
};

/*[AccessAllowed, RsrcCategory, AlwaysOn, MinMode, SafetyHR, MinVoltage, MaxVoltage, EnableFixedTime, EnableStepperWarmUpTime, VoltFixedUpTime, VoltFixedDownTime, VoltStepperExtraUpTime, VoltStepperExtraDownTime, VoltDischargeTime, ModeFixedTime , VregReadyEn, VregReadyErrEn, VregWdogTimer]*/
/*[VoltSeqType, EnableSeqType, ModeSeqType, DrvOwnMask, Reserved]*/
__attribute__((section("pm_ddr_reclaim_pool")))
pm_vrm_vreg_rail_info_type ldo_rail_e[] =
{
    {.AccessAllowed = PM_ACCESS_ALLOWED,    .RsrcCategory = VRM_RSRC_REGULATOR,  .AlwaysOn = PM_OFF,  .MinMode = PM_LPM_MODE_VAL,  .SafetyHR = 96,  .MinVoltage = 530,   .MaxVoltage = 864,   .EnableFixedTime = 300, .EnableStepperWarmUpTime = 0, .VoltFixedUpTime = 0, .VoltFixedDownTime = 0, .VoltStepperExtraUpTime = 0, .VoltStepperExtraDownTime = 0, .VoltDischargeTime = 0, .ModeFixedTime = 20,  .VregReadyEn = PM_SETTLING_EN, .VregReadyErrEn = PM_SETTLING_ERR_EN, .VregWdogTimer = VRM_8X_SETTLING_TIMER, .AopHandling = 0, .VoltSeqType = VRM_GENERIC_SEQ, .EnableSeqType = VRM_GENERIC_SEQ, .ModeSeqType = VRM_GENERIC_SEQ, .DrvOwnMask = PM_DRV_MDMS, .Reserved = 0}, // L1E SDR VDDCX
    {.AccessAllowed = PM_ACCESS_DISALLOWED, .RsrcCategory = VRM_RSRC_REGULATOR,  .AlwaysOn = PM_OFF,  .MinMode = PM_LPM_MODE_VAL,  .SafetyHR = 0,   .MinVoltage = 528,   .MaxVoltage = 1544,  .EnableFixedTime = 300, .EnableStepperWarmUpTime = 0, .VoltFixedUpTime = 0, .VoltFixedDownTime = 0, .VoltStepperExtraUpTime = 0, .VoltStepperExtraDownTime = 0, .VoltDischargeTime = 0, .ModeFixedTime = 20,  .VregReadyEn = PM_SETTLING_EN, .VregReadyErrEn = PM_SETTLING_ERR_EN, .VregWdogTimer = VRM_8X_SETTLING_TIMER, .AopHandling = 0, .VoltSeqType = VRM_GENERIC_SEQ, .EnableSeqType = VRM_GENERIC_SEQ, .ModeSeqType = VRM_GENERIC_SEQ, .DrvOwnMask = PM_DRV_ARC, .Reserved = 0}, // L2E UNUSED
    {.AccessAllowed = PM_ACCESS_ALLOWED,    .RsrcCategory = VRM_RSRC_REGULATOR,  .AlwaysOn = PM_OFF,  .MinMode = PM_LPM_MODE_VAL,  .SafetyHR = 8,   .MinVoltage = 2700,  .MaxVoltage = 3300,  .EnableFixedTime = 300, .EnableStepperWarmUpTime = 0, .VoltFixedUpTime = 0, .VoltFixedDownTime = 0, .VoltStepperExtraUpTime = 0, .VoltStepperExtraDownTime = 0, .VoltDischargeTime = 0, .ModeFixedTime = 20,  .VregReadyEn = PM_SETTLING_EN, .VregReadyErrEn = PM_SETTLING_ERR_EN, .VregWdogTimer = VRM_8X_SETTLING_TIMER, .AopHandling = 0, .VoltSeqType = VRM_GENERIC_SEQ, .EnableSeqType = VRM_GENERIC_SEQ, .ModeSeqType = VRM_GENERIC_SEQ, .DrvOwnMask = PM_DRV_WLANRF, .Reserved = 0}, // L3E AV91C VDD
    {.AccessAllowed = PM_ACCESS_ALLOWED,    .RsrcCategory = VRM_RSRC_REGULATOR,  .AlwaysOn = PM_OFF,  .MinMode = PM_LPM_MODE_VAL,  .SafetyHR = 80,  .MinVoltage = 2600,  .MaxVoltage = 3312,  .EnableFixedTime = 300, .EnableStepperWarmUpTime = 0, .VoltFixedUpTime = 0, .VoltFixedDownTime = 0, .VoltStepperExtraUpTime = 0, .VoltStepperExtraDownTime = 0, .VoltDischargeTime = 0, .ModeFixedTime = 20,  .VregReadyEn = PM_SETTLING_EN, .VregReadyErrEn = PM_SETTLING_ERR_EN, .VregWdogTimer = VRM_8X_SETTLING_TIMER, .AopHandling = 0, .VoltSeqType = VRM_GENERIC_SEQ, .EnableSeqType = VRM_GENERIC_SEQ, .ModeSeqType = VRM_GENERIC_SEQ, .DrvOwnMask = PM_DRV_AUD, .Reserved = 0}, // L4E Touch_VDDH
    {.AccessAllowed = PM_ACCESS_ALLOWED,    .RsrcCategory = VRM_RSRC_REGULATOR,  .AlwaysOn = PM_OFF,  .MinMode = PM_LPM_MODE_VAL,  .SafetyHR = 400, .MinVoltage = 2400,  .MaxVoltage = 3544,  .EnableFixedTime = 300, .EnableStepperWarmUpTime = 0, .VoltFixedUpTime = 0, .VoltFixedDownTime = 0, .VoltStepperExtraUpTime = 0, .VoltStepperExtraDownTime = 0, .VoltDischargeTime = 0, .ModeFixedTime = 20,  .VregReadyEn = PM_SETTLING_EN, .VregReadyErrEn = PM_SETTLING_ERR_EN, .VregWdogTimer = VRM_8X_SETTLING_TIMER, .AopHandling = 0, .VoltSeqType = VRM_GENERIC_SEQ, .EnableSeqType = VRM_GENERIC_SEQ, .ModeSeqType = VRM_GENERIC_SEQ, .DrvOwnMask = PM_DRV_HLOS, .Reserved = 0}, // L5E UFS VCC
    {.AccessAllowed = PM_ACCESS_ALLOWED,    .RsrcCategory = VRM_RSRC_REGULATOR,  .AlwaysOn = PM_OFF,  .MinMode = PM_LPM_MODE_VAL,  .SafetyHR = 240, .MinVoltage = 3000,  .MaxVoltage = 3312,  .EnableFixedTime = 300, .EnableStepperWarmUpTime = 0, .VoltFixedUpTime = 0, .VoltFixedDownTime = 0, .VoltStepperExtraUpTime = 0, .VoltStepperExtraDownTime = 0, .VoltDischargeTime = 0, .ModeFixedTime = 20,  .VregReadyEn = PM_SETTLING_EN, .VregReadyErrEn = PM_SETTLING_ERR_EN, .VregWdogTimer = VRM_8X_SETTLING_TIMER, .AopHandling = 0, .VoltSeqType = VRM_GENERIC_SEQ, .EnableSeqType = VRM_GENERIC_SEQ, .ModeSeqType = VRM_GENERIC_SEQ, .DrvOwnMask = PM_DRV_AUD, .Reserved = 0}, // L6E TMS VLED
    {.AccessAllowed = PM_ACCESS_ALLOWED,    .RsrcCategory = VRM_RSRC_REGULATOR,  .AlwaysOn = PM_OFF,  .MinMode = PM_LPM_MODE_VAL,  .SafetyHR = 304, .MinVoltage = 2500,  .MaxVoltage = 3544,  .EnableFixedTime = 300, .EnableStepperWarmUpTime = 0, .VoltFixedUpTime = 0, .VoltFixedDownTime = 0, .VoltStepperExtraUpTime = 0, .VoltStepperExtraDownTime = 0, .VoltDischargeTime = 0, .ModeFixedTime = 20,  .VregReadyEn = PM_SETTLING_EN, .VregReadyErrEn = PM_SETTLING_ERR_EN, .VregWdogTimer = VRM_8X_SETTLING_TIMER, .AopHandling = 0, .VoltSeqType = VRM_GENERIC_SEQ, .EnableSeqType = VRM_GENERIC_SEQ, .ModeSeqType = VRM_GENERIC_SEQ, .DrvOwnMask = PM_DRV_WPSS, .Reserved = 0}, // L7E WCN3950_Chain0_3P3
};

/*[AccessAllowed, RsrcCategory, AlwaysOn, MinMode, SafetyHR, MinVoltage, MaxVoltage, EnableFixedTime, EnableStepperWarmUpTime, VoltFixedUpTime, VoltFixedDownTime, VoltStepperExtraUpTime, VoltStepperExtraDownTime, VoltDischargeTime, ModeFixedTime , VregReadyEn, VregReadyErrEn, VregWdogTimer]*/
/*[VoltSeqType, EnableSeqType, ModeSeqType, DrvOwnMask, Reserved]*/
__attribute__((section("pm_ddr_reclaim_pool")))
pm_vrm_vreg_rail_info_type smps_rail_b[] =
{
    {.AccessAllowed = PM_ACCESS_ALLOWED,    .RsrcCategory = VRM_RSRC_REGULATOR,  .AlwaysOn = PM_OFF,  .MinMode = PM_RET_MODE_VAL,  .SafetyHR = 0,  .MinVoltage = 320,   .MaxVoltage = 852,   .EnableFixedTime = 500, .EnableStepperWarmUpTime = 0, .VoltFixedUpTime = 0, .VoltFixedDownTime = 0, .VoltStepperExtraUpTime = 20, .VoltStepperExtraDownTime = 20, .VoltDischargeTime = 50, .ModeFixedTime = 20,  .VregReadyEn = PM_SETTLING_EN, .VregReadyErrEn = PM_SETTLING_ERR_EN, .VregWdogTimer = VRM_8X_SETTLING_TIMER, .AopHandling = 0, .VoltSeqType = VRM_GENERIC_SEQ, .EnableSeqType = VRM_GENERIC_SEQ, .ModeSeqType = VRM_GENERIC_SEQ, .DrvOwnMask = PM_DRV_ARC, .Reserved = 0}, // S1B VDD_MODEM
    {.AccessAllowed = PM_ACCESS_DISALLOWED, .RsrcCategory = VRM_RSRC_REGULATOR,  .AlwaysOn = PM_ON,   .MinMode = PM_RET_MODE_VAL,  .SafetyHR = 0,  .MinVoltage = 504,   .MaxVoltage = 888,   .EnableFixedTime = 500, .EnableStepperWarmUpTime = 0, .VoltFixedUpTime = 0, .VoltFixedDownTime = 0, .VoltStepperExtraUpTime = 20, .VoltStepperExtraDownTime = 20, .VoltDischargeTime = 50, .ModeFixedTime = 20,  .VregReadyEn = PM_SETTLING_EN, .VregReadyErrEn = PM_SETTLING_ERR_EN, .VregWdogTimer = VRM_8X_SETTLING_TIMER, .AopHandling = 0, .VoltSeqType = VRM_GENERIC_SEQ, .EnableSeqType = VRM_GENERIC_SEQ, .ModeSeqType = VRM_GENERIC_SEQ, .DrvOwnMask = PM_DRV_ARC, .Reserved = 0}, // S2B VDD_MODEM/VDDMX
    {.AccessAllowed = PM_ACCESS_DISALLOWED, .RsrcCategory = VRM_RSRC_REGULATOR,  .AlwaysOn = PM_OFF,  .MinMode = PM_AUTO_MODE_VAL, .SafetyHR = 0,  .MinVoltage = 320,   .MaxVoltage = 1052,  .EnableFixedTime = 500, .EnableStepperWarmUpTime = 0, .VoltFixedUpTime = 0, .VoltFixedDownTime = 0, .VoltStepperExtraUpTime = 20, .VoltStepperExtraDownTime = 20, .VoltDischargeTime = 50, .ModeFixedTime = 20,  .VregReadyEn = PM_SETTLING_EN, .VregReadyErrEn = PM_SETTLING_ERR_EN, .VregWdogTimer = VRM_8X_SETTLING_TIMER, .AopHandling = 0, .VoltSeqType = VRM_GENERIC_SEQ, .EnableSeqType = VRM_GENERIC_SEQ, .ModeSeqType = VRM_GENERIC_SEQ, .DrvOwnMask = PM_DRV_AOP, .Reserved = 0}, // S3B APC
    {.AccessAllowed = PM_ACCESS_DISALLOWED, .RsrcCategory = VRM_RSRC_REGULATOR,  .AlwaysOn = PM_OFF,  .MinMode = PM_AUTO_MODE_VAL, .SafetyHR = 0,  .MinVoltage = 320,   .MaxVoltage = 1052,  .EnableFixedTime = 500, .EnableStepperWarmUpTime = 0, .VoltFixedUpTime = 0, .VoltFixedDownTime = 0, .VoltStepperExtraUpTime = 20, .VoltStepperExtraDownTime = 20, .VoltDischargeTime = 50, .ModeFixedTime = 20,  .VregReadyEn = PM_SETTLING_EN, .VregReadyErrEn = PM_SETTLING_ERR_EN, .VregWdogTimer = VRM_8X_SETTLING_TIMER, .AopHandling = 0, .VoltSeqType = VRM_GENERIC_SEQ, .EnableSeqType = VRM_GENERIC_SEQ, .ModeSeqType = VRM_GENERIC_SEQ, .DrvOwnMask = PM_DRV_AOP, .Reserved = 0}, // S4B APC
    {.AccessAllowed = PM_ACCESS_ALLOWED,    .RsrcCategory = VRM_RSRC_REGULATOR,  .AlwaysOn = PM_ON,   .MinMode = PM_RET_MODE_VAL,  .SafetyHR = 0,  .MinVoltage = 320,   .MaxVoltage = 1050,  .EnableFixedTime = 500, .EnableStepperWarmUpTime = 0, .VoltFixedUpTime = 0, .VoltFixedDownTime = 0, .VoltStepperExtraUpTime = 20, .VoltStepperExtraDownTime = 20, .VoltDischargeTime = 50, .ModeFixedTime = 20,  .VregReadyEn = PM_SETTLING_EN, .VregReadyErrEn = PM_SETTLING_ERR_EN, .VregWdogTimer = VRM_8X_SETTLING_TIMER, .AopHandling = 0, .VoltSeqType = VRM_GENERIC_SEQ, .EnableSeqType = VRM_GENERIC_SEQ, .ModeSeqType = VRM_GENERIC_SEQ, .DrvOwnMask = PM_DRV_ARC, .Reserved = 0}, // S5B VDDCX
    {.AccessAllowed = PM_ACCESS_ALLOWED,    .RsrcCategory = VRM_RSRC_REGULATOR,  .AlwaysOn = PM_ON,   .MinMode = PM_RET_MODE_VAL,  .SafetyHR = 0,  .MinVoltage = 320,   .MaxVoltage = 952,   .EnableFixedTime = 500, .EnableStepperWarmUpTime = 0, .VoltFixedUpTime = 0, .VoltFixedDownTime = 0, .VoltStepperExtraUpTime = 20, .VoltStepperExtraDownTime = 20, .VoltDischargeTime = 50, .ModeFixedTime = 20,  .VregReadyEn = PM_SETTLING_EN, .VregReadyErrEn = PM_SETTLING_ERR_EN, .VregWdogTimer = VRM_8X_SETTLING_TIMER, .AopHandling = 0, .VoltSeqType = VRM_GENERIC_SEQ, .EnableSeqType = VRM_GENERIC_SEQ, .ModeSeqType = VRM_GENERIC_SEQ, .DrvOwnMask = PM_DRV_ARC, .Reserved = 0}, // S6B VDDA_EBI
    {.AccessAllowed = PM_ACCESS_ALLOWED,    .RsrcCategory = VRM_RSRC_REGULATOR,  .AlwaysOn = PM_ON,   .MinMode = PM_RET_MODE_VAL,  .SafetyHR = 0,  .MinVoltage = 1010,  .MaxVoltage = 1170,  .EnableFixedTime = 500, .EnableStepperWarmUpTime = 0, .VoltFixedUpTime = 0, .VoltFixedDownTime = 0, .VoltStepperExtraUpTime = 20, .VoltStepperExtraDownTime = 20, .VoltDischargeTime = 50, .ModeFixedTime = 20,  .VregReadyEn = PM_SETTLING_EN, .VregReadyErrEn = PM_SETTLING_ERR_EN, .VregWdogTimer = VRM_8X_SETTLING_TIMER, .AopHandling = 0, .VoltSeqType = VRM_GENERIC_SEQ, .EnableSeqType = VRM_GENERIC_SEQ, .ModeSeqType = VRM_GENERIC_SEQ, .DrvOwnMask = PM_DRV_DDR, .Reserved = 0}, // S7B LV Sub Regulator/ LP4x_VDD2/LP5_VDD2H
    {.AccessAllowed = PM_ACCESS_ALLOWED,    .RsrcCategory = VRM_RSRC_REGULATOR,  .AlwaysOn = PM_ON,   .MinMode = PM_AUTO_MODE_VAL, .SafetyHR = 0,  .MinVoltage = 1216,  .MaxVoltage = 1744,  .EnableFixedTime = 500, .EnableStepperWarmUpTime = 0, .VoltFixedUpTime = 0, .VoltFixedDownTime = 0, .VoltStepperExtraUpTime = 20, .VoltStepperExtraDownTime = 20, .VoltDischargeTime = 50, .ModeFixedTime = 20,  .VregReadyEn = PM_SETTLING_EN, .VregReadyErrEn = PM_SETTLING_ERR_EN, .VregWdogTimer = VRM_8X_SETTLING_TIMER, .AopHandling = 0, .VoltSeqType = VRM_GENERIC_SEQ, .EnableSeqType = VRM_GENERIC_SEQ, .ModeSeqType = VRM_GENERIC_SEQ, .DrvOwnMask = PM_DRV_AOP, .Reserved = 0}, // S8B MV Sub Regulator
    {.AccessAllowed = PM_ACCESS_ALLOWED,    .RsrcCategory = VRM_RSRC_REGULATOR,  .AlwaysOn = PM_ON,   .MinMode = PM_AUTO_MODE_VAL, .SafetyHR = 0,  .MinVoltage = 1856,  .MaxVoltage = 2040,  .EnableFixedTime = 500, .EnableStepperWarmUpTime = 0, .VoltFixedUpTime = 0, .VoltFixedDownTime = 0, .VoltStepperExtraUpTime = 20, .VoltStepperExtraDownTime = 20, .VoltDischargeTime = 50, .ModeFixedTime = 20,  .VregReadyEn = PM_SETTLING_EN, .VregReadyErrEn = PM_SETTLING_ERR_EN, .VregWdogTimer = VRM_8X_SETTLING_TIMER, .AopHandling = 0, .VoltSeqType = VRM_GENERIC_SEQ, .EnableSeqType = VRM_GENERIC_SEQ, .ModeSeqType = VRM_GENERIC_SEQ, .DrvOwnMask = PM_DRV_AOP, .Reserved = 0}, // S9B HV Sub Regulator
};

/*[AccessAllowed, RsrcCategory, AlwaysOn, MinMode, SafetyHR, MinVoltage, MaxVoltage, EnableFixedTime, EnableStepperWarmUpTime, VoltFixedUpTime, VoltFixedDownTime, VoltStepperExtraUpTime, VoltStepperExtraDownTime, VoltDischargeTime, ModeFixedTime , VregReadyEn, VregReadyErrEn, VregWdogTimer]*/
/*[VoltSeqType, EnableSeqType, ModeSeqType, DrvOwnMask, Reserved]*/
__attribute__((section("pm_ddr_reclaim_pool")))
pm_vrm_vreg_rail_info_type smps_rail_g[] =
{
 {.AccessAllowed = PM_ACCESS_ALLOWED,  .RsrcCategory = VRM_RSRC_REGULATOR, .AlwaysOn = PM_ON,  .MinMode = PM_RET_MODE_VAL, .SafetyHR = 0,  .MinVoltage = 504,  .MaxVoltage = 888,  .EnableFixedTime = 500, .EnableStepperWarmUpTime = 0, .VoltFixedUpTime = 0, .VoltFixedDownTime = 0, .VoltStepperExtraUpTime = 20, .VoltStepperExtraDownTime = 20, .VoltDischargeTime = 50, .ModeFixedTime = 20,  .VregReadyEn = PM_SETTLING_EN, .VregReadyErrEn = PM_SETTLING_ERR_EN, .VregWdogTimer = VRM_8X_SETTLING_TIMER, .AopHandling = 0, .VoltSeqType = VRM_GENERIC_SEQ, .EnableSeqType = VRM_GENERIC_SEQ, .ModeSeqType = VRM_GENERIC_SEQ, .DrvOwnMask = PM_DRV_ARC, .Reserved = 0}, // S1G VDDMX
};
__attribute__((section("pm_ddr_reclaim_pool")))
pm_vrm_clk_info_type clk_info_a[] =
{
    {.AccessAllowed = PM_ACCESS_DISALLOWED,  .RsrcCategory = VRM_RSRC_XO_BUFFER,  .AlwaysOn = PM_OFF,  .EnableFixedTime = 300,  .EnableSeqType = VRM_GENERIC_SEQ,  .Reserved = 0,  .DrvOwnMask = PM_DRV_ARC,    .ClkReadyEn = PM_SETTLING_EN,  .ClkReadyErrEn = PM_SETTLING_ERR_EN,  .ClkWdogTimer = VRM_4X_SETTLING_TIMER,  .Reserved1 = 0},  // CLK_DIST
    {.AccessAllowed = PM_ACCESS_DISALLOWED,  .RsrcCategory = VRM_RSRC_XO_BUFFER,  .AlwaysOn = PM_OFF,  .EnableFixedTime = 300,  .EnableSeqType = VRM_GENERIC_SEQ,  .Reserved = 0,  .DrvOwnMask = PM_DRV_ARC,    .ClkReadyEn = PM_SETTLING_EN,  .ClkReadyErrEn = PM_SETTLING_ERR_EN,  .ClkWdogTimer = VRM_4X_SETTLING_TIMER,  .Reserved1 = 0},  // EMPTY
    {.AccessAllowed = PM_ACCESS_DISALLOWED,  .RsrcCategory = VRM_RSRC_XO_BUFFER,  .AlwaysOn = PM_OFF,  .EnableFixedTime = 300,  .EnableSeqType = VRM_GENERIC_SEQ,  .Reserved = 0,  .DrvOwnMask = PM_DRV_ARC,    .ClkReadyEn = PM_SETTLING_EN,  .ClkReadyErrEn = PM_SETTLING_ERR_EN,  .ClkWdogTimer = VRM_4X_SETTLING_TIMER,  .Reserved1 = 0},  // EMPTY
    {.AccessAllowed = PM_ACCESS_ALLOWED,     .RsrcCategory = VRM_RSRC_XO_BUFFER,  .AlwaysOn = PM_OFF,  .EnableFixedTime = 300,  .EnableSeqType = VRM_GENERIC_SEQ,  .Reserved = 0,  .DrvOwnMask = PM_DRV_MDMS,   .ClkReadyEn = PM_SETTLING_EN,  .ClkReadyErrEn = PM_SETTLING_ERR_EN,  .ClkWdogTimer = VRM_4X_SETTLING_TIMER,  .Reserved1 = 0},  // RF_CLK1
    {.AccessAllowed = PM_ACCESS_DISALLOWED,  .RsrcCategory = VRM_RSRC_XO_BUFFER,  .AlwaysOn = PM_OFF,  .EnableFixedTime = 300,  .EnableSeqType = VRM_GENERIC_SEQ,  .Reserved = 0,  .DrvOwnMask = PM_DRV_MDMS,   .ClkReadyEn = PM_SETTLING_EN,  .ClkReadyErrEn = PM_SETTLING_ERR_EN,  .ClkWdogTimer = VRM_4X_SETTLING_TIMER,  .Reserved1 = 0},  // RF_CLK2
    {.AccessAllowed = PM_ACCESS_DISALLOWED,  .RsrcCategory = VRM_RSRC_XO_BUFFER,  .AlwaysOn = PM_OFF,  .EnableFixedTime = 300,  .EnableSeqType = VRM_GENERIC_SEQ,  .Reserved = 0,  .DrvOwnMask = PM_DRV_ARC,    .ClkReadyEn = PM_SETTLING_EN,  .ClkReadyErrEn = PM_SETTLING_ERR_EN,  .ClkWdogTimer = VRM_4X_SETTLING_TIMER,  .Reserved1 = 0},  // RF_CLK3
    {.AccessAllowed = PM_ACCESS_DISALLOWED,  .RsrcCategory = VRM_RSRC_XO_BUFFER,  .AlwaysOn = PM_OFF,  .EnableFixedTime = 300,  .EnableSeqType = VRM_GENERIC_SEQ,  .Reserved = 0,  .DrvOwnMask = PM_DRV_ARC,    .ClkReadyEn = PM_SETTLING_EN,  .ClkReadyErrEn = PM_SETTLING_ERR_EN,  .ClkWdogTimer = VRM_4X_SETTLING_TIMER,  .Reserved1 = 0},  // RF_CLK4
    {.AccessAllowed = PM_ACCESS_ALLOWED,     .RsrcCategory = VRM_RSRC_XO_BUFFER,  .AlwaysOn = PM_OFF,  .EnableFixedTime = 300,  .EnableSeqType = VRM_GENERIC_SEQ,  .Reserved = 0,  .DrvOwnMask = PM_DRV_WLANRF, .ClkReadyEn = PM_SETTLING_EN,  .ClkReadyErrEn = PM_SETTLING_ERR_EN,  .ClkWdogTimer = VRM_4X_SETTLING_TIMER,  .Reserved1 = 0},  // RF_CLK5
    {.AccessAllowed = PM_ACCESS_ALLOWED,     .RsrcCategory = VRM_RSRC_XO_BUFFER,  .AlwaysOn = PM_OFF,  .EnableFixedTime = 300,  .EnableSeqType = VRM_GENERIC_SEQ,  .Reserved = 0,  .DrvOwnMask = PM_DRV_ARC,    .ClkReadyEn = PM_SETTLING_EN,  .ClkReadyErrEn = PM_SETTLING_ERR_EN,  .ClkWdogTimer = VRM_4X_SETTLING_TIMER,  .Reserved1 = 0},  // LN_BB_CLK1
    {.AccessAllowed = PM_ACCESS_ALLOWED,     .RsrcCategory = VRM_RSRC_XO_BUFFER,  .AlwaysOn = PM_OFF,  .EnableFixedTime = 300,  .EnableSeqType = VRM_GENERIC_SEQ,  .Reserved = 0,  .DrvOwnMask = PM_DRV_HLOS,   .ClkReadyEn = PM_SETTLING_EN,  .ClkReadyErrEn = PM_SETTLING_ERR_EN,  .ClkWdogTimer = VRM_4X_SETTLING_TIMER,  .Reserved1 = 0},  // LN_BB_CLK2
    {.AccessAllowed = PM_ACCESS_ALLOWED,     .RsrcCategory = VRM_RSRC_XO_BUFFER,  .AlwaysOn = PM_OFF,  .EnableFixedTime = 300,  .EnableSeqType = VRM_GENERIC_SEQ,  .Reserved = 0,  .DrvOwnMask = PM_DRV_WLANRF, .ClkReadyEn = PM_SETTLING_EN,  .ClkReadyErrEn = PM_SETTLING_ERR_EN,  .ClkWdogTimer = VRM_4X_SETTLING_TIMER,  .Reserved1 = 0},  // LN_BB_CLK3
    {.AccessAllowed = PM_ACCESS_DISALLOWED,  .RsrcCategory = VRM_RSRC_XO_BUFFER,  .AlwaysOn = PM_OFF,  .EnableFixedTime = 300,  .EnableSeqType = VRM_GENERIC_SEQ,  .Reserved = 0,  .DrvOwnMask = PM_DRV_ARC,    .ClkReadyEn = PM_SETTLING_EN,  .ClkReadyErrEn = PM_SETTLING_ERR_EN,  .ClkWdogTimer = VRM_4X_SETTLING_TIMER,  .Reserved1 = 0},  // EMPTY
    {.AccessAllowed = PM_ACCESS_DISALLOWED,  .RsrcCategory = VRM_RSRC_XO_BUFFER,  .AlwaysOn = PM_OFF,  .EnableFixedTime = 300,  .EnableSeqType = VRM_GENERIC_SEQ,  .Reserved = 0,  .DrvOwnMask = PM_DRV_ARC,    .ClkReadyEn = PM_SETTLING_EN,  .ClkReadyErrEn = PM_SETTLING_ERR_EN,  .ClkWdogTimer = VRM_4X_SETTLING_TIMER,  .Reserved1 = 0},  // EMPTY
    {.AccessAllowed = PM_ACCESS_DISALLOWED,  .RsrcCategory = VRM_RSRC_XO_BUFFER,  .AlwaysOn = PM_OFF,  .EnableFixedTime = 300,  .EnableSeqType = VRM_GENERIC_SEQ,  .Reserved = 0,  .DrvOwnMask = PM_DRV_ARC,    .ClkReadyEn = PM_SETTLING_EN,  .ClkReadyErrEn = PM_SETTLING_ERR_EN,  .ClkWdogTimer = VRM_4X_SETTLING_TIMER,  .Reserved1 = 0},  // DIV_CLK1
    {.AccessAllowed = PM_ACCESS_DISALLOWED,  .RsrcCategory = VRM_RSRC_XO_BUFFER,  .AlwaysOn = PM_OFF,  .EnableFixedTime = 300,  .EnableSeqType = VRM_GENERIC_SEQ,  .Reserved = 0,  .DrvOwnMask = PM_DRV_ARC,    .ClkReadyEn = PM_SETTLING_EN,  .ClkReadyErrEn = PM_SETTLING_ERR_EN,  .ClkWdogTimer = VRM_4X_SETTLING_TIMER,  .Reserved1 = 0},  // EMPTY
    {.AccessAllowed = PM_ACCESS_DISALLOWED,  .RsrcCategory = VRM_RSRC_XO_BUFFER,  .AlwaysOn = PM_OFF,  .EnableFixedTime = 300,  .EnableSeqType = VRM_GENERIC_SEQ,  .Reserved = 0,  .DrvOwnMask = PM_DRV_ARC,    .ClkReadyEn = PM_SETTLING_EN,  .ClkReadyErrEn = PM_SETTLING_ERR_EN,  .ClkWdogTimer = VRM_4X_SETTLING_TIMER,  .Reserved1 = 0},  // SLEEP_CLK1
};

/*Name, PmicIndex, PeriphType, PeriphId, AccessAllowed, SlaveId, BaseAddr, RsrcCategory, EnableAddrOff, EnableFixedTime, EnableSeqType, ModeAddrOff, ModeFixedTime, ModeSeqType,
  VoltAddrOff, VoltFixedTime, VoltSeqType, MaxVoltage, DrvOwnMask, Reserved*/
__attribute__((section("pm_ddr_reclaim_pool")))
pm_vrm_target_rsrc_info_type target_rsrc_info[] =
{
  {"vreg.sp", 0, PM_VRM_PERIPH_VREG, 1, {PM_ACCESS_DISALLOWED, 0x1, 0x3E00, VRM_RSRC_XO_BUFFER, 0x80, 420, VRM_PMIC_WRITE_SEQ, 0x00, 0, VRM_NO_PMIC_SEQ, 0x00, 0, VRM_NO_PMIC_SEQ, 0, PM_DRV_HLOS, 0}},
  {"gpio.sp", 0, PM_VRM_PERIPH_GPIO, 7, {PM_ACCESS_DISALLOWED, 0x1, 0x8E00, VRM_RSRC_XO_BUFFER, 0x46, 20,  VRM_PMIC_WRITE_SEQ, 0x00, 0, VRM_NO_PMIC_SEQ, 0x00, 0, VRM_NO_PMIC_SEQ, 0, PM_DRV_HLOS, 0}},
  {"rclkha1", 0, PM_VRM_PERIPH_CLK,  5, {PM_ACCESS_ALLOWED,    0x0, 0x5400, VRM_RSRC_REGULATOR, 0x45, 20,  VRM_PMIC_WRITE_SEQ, 0x00, 0, VRM_NO_PMIC_SEQ, 0x00, 0, VRM_NO_PMIC_SEQ, 0, PM_DRV_MDMS, 0}},
  {"gpioi7",  8, PM_VRM_PERIPH_GPIO, 7, {PM_ACCESS_ALLOWED,    0x8, 0xC600, VRM_RSRC_XO_BUFFER, 0x44, 200, VRM_PMIC_WRITE_SEQ, 0x00, 0, VRM_NO_PMIC_SEQ, 0x00, 0, VRM_NO_PMIC_SEQ, 0, PM_DRV_WLANRF, 0}},
  {"gpioi10", 8, PM_VRM_PERIPH_GPIO, 10,{PM_ACCESS_ALLOWED,    0x8, 0xC900, VRM_RSRC_XO_BUFFER, 0x44, 20,  VRM_PMIC_WRITE_SEQ, 0x00, 0, VRM_NO_PMIC_SEQ, 0x00, 0, VRM_NO_PMIC_SEQ, 0, PM_DRV_WLANRF, 0}},
};


__attribute__((section("pm_ddr_reclaim_pool")))
pm_vrm_pstm_rsrc_info_type pstm_a[] =
{
  { .pbs_name = "vrm.aoss", .LowVal = 0x01, .HighVal = 0x02, .SettlingTime = 900, .DrvOwnMask = PM_DRV_AOP, .DefaultVal = 1, .AccessAllowed = PM_ACCESS_ALLOWED, .RsrcCategory = VRM_RSRC_PSTM, .EnableSeqType = VRM_GENERIC_SEQ }, //0-AOSS_Sleep 1-AOSS_Wake
  { .pbs_name = "vrm.soc",  .LowVal = 0x03, .HighVal = 0x04, .SettlingTime = 900, .DrvOwnMask = PM_DRV_AUD|PM_DRV_DDR|PM_DRV_MDMS|PM_DRV_TZ, .DefaultVal = 1, .AccessAllowed = PM_ACCESS_ALLOWED, .RsrcCategory = VRM_RSRC_PSTM, .EnableSeqType = VRM_GENERIC_SEQ }, //0-SOC_Sleep 1-SOC_Wake
  { .pbs_name = "vrm.wlan", .LowVal = 0x06, .HighVal = 0x05, .SettlingTime = 900, .DrvOwnMask = PM_DRV_WLANBB, .DefaultVal = 0, .AccessAllowed = PM_ACCESS_ALLOWED, .RsrcCategory = VRM_RSRC_PSTM, .EnableSeqType = VRM_GENERIC_SEQ }, //0-WLAN_WA_DISENGAGE 1- WLAN_ENGAGE
  { .pbs_name = "vrm.sd",   .LowVal = 0x07, .HighVal = 0x09, .SettlingTime = 900, .DrvOwnMask = PM_DRV_HLOS, .DefaultVal = 1, .AccessAllowed = PM_ACCESS_ALLOWED, .RsrcCategory = VRM_RSRC_PSTM, .EnableSeqType = VRM_GENERIC_SEQ }, //0-SD_VDD_Disable 1-SD_VDD_Enable
  { .pbs_name = "vrm.px2",  .LowVal = 0x08, .HighVal = 0x0A, .SettlingTime = 900, .DrvOwnMask = PM_DRV_HLOS, .DefaultVal = 1, .AccessAllowed = PM_ACCESS_ALLOWED, .RsrcCategory = VRM_RSRC_PSTM, .EnableSeqType = VRM_GENERIC_SEQ }, //0-PX2_Disable 1-PX2_Enable
};

uint32 num_of_target_rsrc[]= {sizeof(target_rsrc_info)/sizeof(target_rsrc_info[0])} ;

uint32 num_of_ldo[] = {0,sizeof(ldo_rail_b)/sizeof(ldo_rail_b[0]),0,0,sizeof(ldo_rail_e)/sizeof(ldo_rail_e[0]),0,0,0,0,0,0,0,0,0};

uint32 num_of_smps[] = {0,sizeof(smps_rail_b)/sizeof(smps_rail_b[0]),0,0,0,0,sizeof(smps_rail_g)/sizeof(smps_rail_g[0]),0,0,0,0,0,0,0};

uint32 num_of_bob[] = {0,0,0,0,0,0,0,0,0,0,0,0,0,0};

uint32 num_of_pstm_seq[] = {sizeof(pstm_a)/sizeof(pstm_a[0]),0,0,0,0,0,0,0,0,0,0,0,0,0};

__attribute__((section("pm_dram_reclaim_pool")))
pm_vrm_vreg_rail_info_type* ldo_rail[] =
{
 NULL, ldo_rail_b, NULL, NULL, ldo_rail_e, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL
};

__attribute__((section("pm_dram_reclaim_pool")))
pm_vrm_vreg_rail_info_type* smps_rail[] =
{
 NULL, smps_rail_b, NULL, NULL, NULL, NULL, smps_rail_g, NULL, NULL, NULL, NULL, NULL, NULL, NULL
};

__attribute__((section("pm_dram_reclaim_pool")))
pm_vrm_vreg_rail_info_type* bob_rail[] =
{
 NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL
};

__attribute__((section("pm_dram_reclaim_pool")))
pm_vrm_pstm_rsrc_info_type* pstm_info[] =
{
 pstm_a, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL
};
 
__attribute__((section("pm_dram_reclaim_pool")))
pm_vrm_clk_info_type* clk_info[]=
{
 clk_info_a, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL
};

__attribute__((section("pm_dram_reclaim_pool")))
uint32 rpmh_drv_id[] = {(uint32)RSC_DRV_AOP};

