#ifndef __SPI_DEFINES_H__
#define __SPI_DEFINES_H__


/*=============================================================================   
    @file  i2c_config.h
    @brief interface to device configuration
   
    Copyright (c) 2022 Qualcomm Technologies, Incorporated.
                        All rights reserved.
    Qualcomm Technologies, Confidential and Proprietary.
===============================================================================*/

/*=============================================================================
                              EDIT HISTORY
 when       who     what, where, why
 --------   ---     -----------------------------------------------------------
 03/30/22   PS      Added new include file.
 
=============================================================================*/


#define TLMM_GPIO_CFG(gpio, func, dir, pull, drive) \
                          (((gpio) & 0x3FF) << 4  | \
                           ((func) & 0xF  ) << 0  | \
                           ((dir)  & 0x1  ) << 14 | \
                           ((pull) & 0x3  ) << 15 | \
                           ((drive)& 0xF  ) << 17)

#define TLMM_GPIO_INPUT      0x0
#define TLMM_GPIO_OUTPUT     0x1
#define TLMM_GPIO_NO_PULL    0x0
#define TLMM_GPIO_PULL_DOWN  0x1
#define TLMM_GPIO_PULL_UP    0x3
#define TLMM_GPIO_6MA        0x2


#define QUPV3_0_CORE_BASE_ADDRESS        0x00900000
#define QUPV3_0_CORE_COMMON_BASE_ADDRESS 0x009C0000

#define QUPV3_1_CORE_BASE_ADDRESS        0x00A00000
#define QUPV3_1_CORE_COMMON_BASE_ADDRESS 0x00AC0000

// set GPIOs for the defined cores
// TLMM_GPIO_CFG(gpio, func, dir, pull, drive)
#define SPI_01_MISO TLMM_GPIO_CFG(4,  1, TLMM_GPIO_INPUT,  TLMM_GPIO_PULL_DOWN, TLMM_GPIO_6MA)
#define SPI_01_MOSI TLMM_GPIO_CFG(5,  1, TLMM_GPIO_OUTPUT, TLMM_GPIO_PULL_DOWN, TLMM_GPIO_6MA)
#define SPI_01_CLK  TLMM_GPIO_CFG(34,  1, TLMM_GPIO_OUTPUT, TLMM_GPIO_NO_PULL,   TLMM_GPIO_6MA)
#define SPI_01_CS_0 TLMM_GPIO_CFG(35,  1, TLMM_GPIO_OUTPUT, TLMM_GPIO_PULL_DOWN, TLMM_GPIO_6MA)

#define SPI_02_MISO TLMM_GPIO_CFG(10,  1, TLMM_GPIO_INPUT,  TLMM_GPIO_PULL_DOWN, TLMM_GPIO_6MA)
#define SPI_02_MOSI TLMM_GPIO_CFG(11,  1, TLMM_GPIO_OUTPUT, TLMM_GPIO_PULL_DOWN, TLMM_GPIO_6MA)
#define SPI_02_CLK  TLMM_GPIO_CFG(12,  1, TLMM_GPIO_OUTPUT, TLMM_GPIO_NO_PULL,   TLMM_GPIO_6MA)
#define SPI_02_CS_0 TLMM_GPIO_CFG(13,  1, TLMM_GPIO_OUTPUT, TLMM_GPIO_PULL_DOWN, TLMM_GPIO_6MA)

#define SPI_03_MISO TLMM_GPIO_CFG(14,  1, TLMM_GPIO_INPUT,  TLMM_GPIO_PULL_DOWN, TLMM_GPIO_6MA)
#define SPI_03_MOSI TLMM_GPIO_CFG(15,  1, TLMM_GPIO_OUTPUT, TLMM_GPIO_PULL_DOWN, TLMM_GPIO_6MA)
#define SPI_03_CLK  TLMM_GPIO_CFG(16,  1, TLMM_GPIO_OUTPUT, TLMM_GPIO_NO_PULL,   TLMM_GPIO_6MA)
#define SPI_03_CS_0 TLMM_GPIO_CFG(17,  1, TLMM_GPIO_OUTPUT, TLMM_GPIO_PULL_DOWN, TLMM_GPIO_6MA)

#define SPI_04_MISO TLMM_GPIO_CFG(18,  1, TLMM_GPIO_INPUT,  TLMM_GPIO_PULL_DOWN, TLMM_GPIO_6MA)
#define SPI_04_MOSI TLMM_GPIO_CFG(19,  1, TLMM_GPIO_OUTPUT, TLMM_GPIO_PULL_DOWN, TLMM_GPIO_6MA)
#define SPI_04_CLK  TLMM_GPIO_CFG(20,  1, TLMM_GPIO_OUTPUT, TLMM_GPIO_NO_PULL,   TLMM_GPIO_6MA)
#define SPI_04_CS_0 TLMM_GPIO_CFG(21,  1, TLMM_GPIO_OUTPUT, TLMM_GPIO_PULL_DOWN, TLMM_GPIO_6MA)

#define SPI_05_MISO TLMM_GPIO_CFG(8,  1, TLMM_GPIO_INPUT,  TLMM_GPIO_PULL_DOWN, TLMM_GPIO_6MA)
#define SPI_05_MOSI TLMM_GPIO_CFG(9,  1, TLMM_GPIO_OUTPUT, TLMM_GPIO_PULL_DOWN, TLMM_GPIO_6MA)
#define SPI_05_CLK  TLMM_GPIO_CFG(6,  1, TLMM_GPIO_OUTPUT, TLMM_GPIO_NO_PULL,   TLMM_GPIO_6MA)
#define SPI_05_CS_0 TLMM_GPIO_CFG(7,  1, TLMM_GPIO_OUTPUT, TLMM_GPIO_PULL_DOWN, TLMM_GPIO_6MA)

#define SPI_06_MISO TLMM_GPIO_CFG(0,  1, TLMM_GPIO_INPUT,  TLMM_GPIO_PULL_DOWN, TLMM_GPIO_6MA)
#define SPI_06_MOSI TLMM_GPIO_CFG(1,  1, TLMM_GPIO_OUTPUT, TLMM_GPIO_PULL_DOWN, TLMM_GPIO_6MA)
#define SPI_06_CLK  TLMM_GPIO_CFG(2,  1, TLMM_GPIO_OUTPUT, TLMM_GPIO_NO_PULL,   TLMM_GPIO_6MA)
#define SPI_06_CS_0 TLMM_GPIO_CFG(3,  1, TLMM_GPIO_OUTPUT, TLMM_GPIO_PULL_DOWN, TLMM_GPIO_6MA)

#define SPI_07_MISO TLMM_GPIO_CFG(50,  1, TLMM_GPIO_INPUT,  TLMM_GPIO_PULL_DOWN, TLMM_GPIO_6MA)
#define SPI_07_MOSI TLMM_GPIO_CFG(51,  1, TLMM_GPIO_OUTPUT, TLMM_GPIO_PULL_DOWN, TLMM_GPIO_6MA)
#define SPI_07_CLK  TLMM_GPIO_CFG(26,  1, TLMM_GPIO_OUTPUT, TLMM_GPIO_NO_PULL,   TLMM_GPIO_6MA)
#define SPI_07_CS_0 TLMM_GPIO_CFG(27,  1, TLMM_GPIO_OUTPUT, TLMM_GPIO_PULL_DOWN, TLMM_GPIO_6MA)

#define SPI_08_MISO TLMM_GPIO_CFG(31,  1, TLMM_GPIO_INPUT,  TLMM_GPIO_PULL_DOWN, TLMM_GPIO_6MA)
#define SPI_08_MOSI TLMM_GPIO_CFG(32,  1, TLMM_GPIO_OUTPUT, TLMM_GPIO_PULL_DOWN, TLMM_GPIO_6MA)
#define SPI_08_CLK  TLMM_GPIO_CFG(22,  1, TLMM_GPIO_OUTPUT, TLMM_GPIO_NO_PULL,   TLMM_GPIO_6MA)
#define SPI_08_CS_0 TLMM_GPIO_CFG(23,  1, TLMM_GPIO_OUTPUT, TLMM_GPIO_PULL_DOWN, TLMM_GPIO_6MA)

#define SPI_09_MISO TLMM_GPIO_CFG(24,  1, TLMM_GPIO_INPUT,  TLMM_GPIO_PULL_DOWN, TLMM_GPIO_6MA)
#define SPI_09_MOSI TLMM_GPIO_CFG(25,  1, TLMM_GPIO_OUTPUT, TLMM_GPIO_PULL_DOWN, TLMM_GPIO_6MA)
#define SPI_09_CLK  TLMM_GPIO_CFG(51,  2, TLMM_GPIO_OUTPUT, TLMM_GPIO_NO_PULL,   TLMM_GPIO_6MA)
#define SPI_09_CS_0 TLMM_GPIO_CFG(50,  2, TLMM_GPIO_OUTPUT, TLMM_GPIO_PULL_DOWN, TLMM_GPIO_6MA)

#define SPI_10_MISO TLMM_GPIO_CFG(91,  1, TLMM_GPIO_INPUT,  TLMM_GPIO_PULL_DOWN, TLMM_GPIO_6MA)
#define SPI_10_MOSI TLMM_GPIO_CFG(90,  1, TLMM_GPIO_OUTPUT, TLMM_GPIO_PULL_DOWN, TLMM_GPIO_6MA)
#define SPI_10_CLK  TLMM_GPIO_CFG(48,  2, TLMM_GPIO_OUTPUT, TLMM_GPIO_NO_PULL,   TLMM_GPIO_6MA)
#define SPI_10_CS_0 TLMM_GPIO_CFG(43,  2, TLMM_GPIO_OUTPUT, TLMM_GPIO_PULL_DOWN, TLMM_GPIO_6MA)

#endif
