// Copyright (c) 2017, 2020 Qualcomm Technologies, Inc.  All Rights Reserved.
// Qualcomm Technologies Proprietary and Confidential.
/**
* @addtogroup CAppLoader
* @{
  Class CAppLoader implements \link IAppLoader \endlink interface.
  
  The class ID `AppLoader` is not included in the default privilege set. It needs to be added to the 
  privileges section in the metadata to allow the TA to use the CAppLoader class.
*/
// This class provides an interface to load Secure Applications in QSEE
//
#pragma once
// AUTOGENERATED FILE: DO NOT EDIT

#include <stdint.h>
#include "object.h"

#define CAppLoader_UID UINT32_C(3)


